### ISSUE TITLE
ECHO: HTS Age/Sex Disagg Male Helper for Disagg Tool

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#10]
**Task 1**: Choose an OU from the PNSUXIM HTS dataset with all FY17 quarters and APR total, for POS, NEG, and TOTAL (include all age/sex data) (add Q1 data) 

- Assigned to Shazad
- Use Pivot table created by Imran to decide which OU to choose.  will Choose Botswana, which is 100% complte for HTS_TST. 

SharePoint Folder [HERE](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Task 2**: Create completeness checks for finer age sex bands to support SI advisors in priorities of focus for 1 (Output should be an easy way to review by PSNU/SDM where HTS age/sex data for APR17 was incomplete (should be easy to modify to be quarterly) 

**Row**:  PSNU/SDM
**Columns**: 
1) Total Positives for PSNU/SDM (from Datapack) 
2) FY17 % Adult Positives that were men for that PSNU and SDM) (excluding unknowns, excluding 6 modalities see excel file for details) 
3) Total Men identified pos (excluding unknown in FY17) 

**Input Tab**: (to calculate Column 1)  
1) Total PSNU Adult HTS Pos (Column I of the HTS Target Tab in Datapack)
2) % of Adult Distribution of Pos Tests for that SDM (Columns P-Y of HTS Target Tab in Datapack)
placeholder: Total PSNU Adult HTS Pos (Column I of the HTS Target Tab in Datapack)2) Placeholder: % of Adult Distribution of Pos Tests for that SDM (Columns P-Y of HTS Target Tab in Datapack)

**Comment by HoustonJamie** [comment]
How do I add kimi? Or can only ICPI do that? Trying to embrace technology :)

**Comment by shazadahmed10** [comment]
@HoustonJamie i added Kimi! There's an 'assignees' menu at the top right of the page that you can toggle with

**Comment by HoustonJamie** [comment]
Thanks, was on mobile version (assignees only listed on the desktop one)

Got it!

Sent from my iPhone

On Feb 20, 2018, at 10:06 AM, shazadahmed10 <notifications@github.com<mailto:notifications@github.com>> wrote:


@HoustonJamie<https://github.com/houstonjamie> i added Kimi! There's an 'assignees' menu at the top right of the page that you can toggle with

**Comment by kimisatoPC** [comment]
Thanks, all! I'm still figuring out Github. There's no actual document uploaded here that I should review, right?

**Comment by shazadahmed10** [comment]
@kimisatoPC no doc, but I am producing an excel template that will display the items outlined in the first post in this thread. Our convo today will build off of that

**Comment by shazadahmed10** [comment]
To-do's 
-replace current dataset with v3 FactView so PSNUs matchup between FactView and Datapack
-hide math columns and add columns per modality adult male POS needed to fill gap between Fy17 and FY19

**Comment by jb3436** [comment]
This task will be the base solution for OUs that have 100% completeness. Will open a second ticket for the more complex methods that need to be used for OUs with incomplete age/sex disaggs.

**Comment by shazadahmed10** [comment]
Update: reviewed by Jamie. Anticipated need for SSudan to use this tool. 

To-Dos: -QC static tables 
-add finer age bands slicer and sex slicer

**Comment by jb3436** [comment]
Update - South Sudan is using a version of this tool see ticket #24 discussing their SNU x Age/Sex HTS yield targeting.

**Comment by shazadahmed10** [comment]
Created this tool for SSudan ans sent to Tat'Yana at 11:15am Thursday

**Comment by shazadahmed10** [comment]
Link to SSudan tool: 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/South%20Sudan/South%20Sudan%20HTS_Fy19%20Male%20Gap%20Tool.xlsx

**Comment by shazadahmed10** [comment]
tweaks need to be made - using fine age band slicer produces incorrect numbers. 
underlying formulas need to be adjusted to account for changing modalities in underlying pivot tables when slicers are used

**Comment by shazadahmed10** [comment]
connect this tool to Rasta table output - ticket #46

**Comment by jb3436** [comment]
Since this tool was used across multiple OUs for a variety of analyses - closing this ticket for this week. Will continue to use the final product as a resource to respond to requests for next week. @shazadahmed10 @imujawar @HoustonJamie any other comments?

**Comment by HoustonJamie** [comment]
I think Shazad was working on issue we found yesterday during QC and considering adapting to the Rasta graphic. Where did that end up?

Sent from my iPhone

On Feb 23, 2018, at 3:38 PM, Jasmine Buttolph <notifications@github.com<mailto:notifications@github.com>> wrote:


Since this tool was used across multiple OUs for a variety of analyses - closing this ticket for this week. Will continue to use the final product as a resource to respond to requests for next week. @shazadahmed10<https://github.com/shazadahmed10> @imujawar<https://github.com/imujawar> @HoustonJamie<https://github.com/houstonjamie> any other comments?

**Comment by shazadahmed10** [comment]
I finished tweaking the tool...I will do another QC, post online and close the ticket henceforth.

**Comment by shazadahmed10** [comment]
tool finished and QC;ed. Posted on sharepoint
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/South%20Sudan/South%20Sudan%20HTS_Fy19%20Male%20Gap%20Tool.xlsx

**Comment by shazadahmed10** [comment]
In the end, the tool was used by Haiti and Moz. 
Haiti used as is(to my knowledge), while Moz went a step further and filled in PSNUs with 0s with distributions from similar PSNUs. 'Similar' PSNUs were determined by other PSNUs with similar TX_CURR and PLHIV. 

Moz: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Mozambique/Moz%20Rasta%20Table%20Tool.xlsx

Haiti: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Haiti/Haiti%20Rasta%20Table%20Tool%20V2.xlsx
