### ISSUE TITLE
Haiti urgent request: need QC for 2 new partner performance slides

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/COP18#105]
I am requesting help QC-ing 2 new partner performance slides: one w/ FY17 APR data and one w/ FY17 Q1 data.  The slides are posted to the Ad Hoc analyses folder (version Feb 28_revised_2 slides only).  This is somewhat urgent as a DP requested this review before the Haiti outbrief in 3 hrs.  Thanks.

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd-Hoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by mehtasp** [comment]
QC completed using Pano and FY18Q1 Factview SitexIM dataset. Closing ticket.
