### ISSUE TITLE
Urgent DREAMS OVC Disaggs by Service Area for Uganda

### ISSUE THREAD

**Issue by hessionra** [ICPI/COP18#108]
Currently being fleshed out, assigned to @shapaklyak @kschlenker @erinschelar.

**Comment by shapaklyak** [comment]
Need: Age/Sex disaggs for DREAMS service areas for Uganda. 

Task: Calculate proportions based on FY17 APR results, using DREAMS FY17 Dashboard

Sent to @kschlenker & @erinschelar 

Proportions file saved in [Ad-hoc analysis folder](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D):


![image](https://user-images.githubusercontent.com/5234106/36812215-64c9c92c-1c9e-11e8-87f1-b5eeb540ca32.png)
