### ISSUE TITLE
Global HTS_TST and HTST_TST_POS Compelteness

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#11]
Gloabl HTS_TST and HTS_TST_POS completeness review for each OU, SDM, and SNU. 
Assigned to Imran - Building off of ticket #10 's contents.

**Comment by achafetz** [comment]
underlying data for tool posted to [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)

**Comment by achafetz** [comment]
pull request with the [R script](https://github.com/ICPI/COP18/blob/master/echo_data.R)

Aggregated so no DSD/TA. We can change this.

**Comment by imujawar** [comment]
Added [R code](https://github.com/ICPI/COP18/blob/master/echoEcho.R) to create dataset to assess completeness for Fine Age vs. Total Numerator.

**Comment by imujawar** [comment]
Updated [R code](https://github.com/ICPI/COP18/blob/master/echoEcho.R), including Modality data by Sex and Unknown percents.

Tool posted on PEPFAR SharePoint, file name: [HTS_TST_Fine_comp_20180221_updated_v2](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

**Comment by HoustonJamie** [comment]
Shared tool with Nigeria team last night, overall in good shape.  A few small comments:

1 | Can you update conditional formatting for SDM  completeness, only flag male if collumn before it is flagged? (will make it easier to read) 
2 | Can you add a flag to determine districts above 80% of cumulative HTS_POS volume   if sorted by C large to small (only really need to review high burden districts)  
3 | Add the % finer age/sex breakdown of the 25-49 age bands for HTS (i think this is the math but can you double check?) 

a.     Create   same layout as disag tool but will need to add input for completeness check   for simplicity
--
i.     (M/F ratio of FY17 25-49 POS)* (1-completeness check % (columns   )/8 (for male)
ii.     (F/M ratio of FY17 25-49 POS)* (1-completeness check % (columns   )/8 (for female)
iii.     (M/F ratio of FY17 25-49 NEG)* (1-completeness check % (columns   )/8 (for male)
iv.     (F/M ratio of FY17 25-49 NEG)* (1-completeness check % (columns   )/8 (for female)

**Comment by imujawar** [comment]
Made edits as suggested. Created variables for Unknown Sex distribution for 25-49 Age bands, and Male-Female distribution for that age band. Posted tool on [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDisagg%20Tools%2FGlobal%5FHTS%5Fcompleteness&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence). File name: **HTS_TST_Fine_comp_20180224_updated**. 

For the current tool, one needs to use the slicers for Period, OperatingUnit, Modality, and Indicator (HTS_TST, HTS_TST_POS, HTS_TST_NEG). 
![image](https://user-images.githubusercontent.com/18144056/36640519-7efb74ec-19ee-11e8-9570-0f990a35c83a.png)

**Comment by imujawar** [comment]
Updated tool with columns with proportions for the 4 age-bands: 25-29, 30-34, 35-39, 40-49 for Females and Males. File name: **HTS_TST_Fine_comp_20180226.zip**

File posted on [PEPFAR SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDisagg%20Tools%2FGlobal_HTS_completeness&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence).
