### ISSUE TITLE
KP Visualization Dashboard - Due 2/21 AM

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#12]
From Trista:
"I’m trying to pull some data for various countries here at RPM and noticed that the KP Visualization tab on the dashboard is stuck on the Kenya comparison of KP vs. Gen Pop ART linkage (middle graph) no matter which country is selected. Is this something you might be able to fix quickly so that we can use the data for slides on Wednesday?"
Approved by ICPI
Assigned to Pooja and Kimi

**Comment by pvinayak001** [comment]
Issue fixed and new version uploaded [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/ICPI%20Data%20Store/ICPI%20Approved%20Tools%20(most%20current%20version)/Key%20Populations%20Dashboard/ICPI_KeyPops_FY17Q4_Cleaned_KP_Dashboard_20180220.xlsx
): 

I did a QC against Pano for the updated table only. Noted that TX_NEW KP disags for FY17 are not showing up in Pano. Submitted a ticket to the Pano team on this.

**Comment by jb3436** [comment]
Thanks for emailing Trista @pvinayak001 !
