### ISSUE TITLE
COP21 Cameroon PAW Dossier

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#139]
**OU**: Cameroon 
**Request**:  Support analysis of COP treatment targets vs PLHIV numbers and adding a custom org unit (zone, one higher than SNU1) 
**PPM**: Approved (request from Chair/PPM: Sally Blatz) 
**Date Request**: 3/30/21
**Preferred Delivery Date:** TBD?

**Country POCs:**  
•	Colince Keleko (CDC): "Keleko Gueatia, Leonard C. (CDC/DDPHSIS/CGH/DGHT)" <vik7@cdc.gov>
•	Zach Zeh (USAID): "Zeh Akiy, Zacheaus" <zzehakiy@usaid.gov>
•	Ghislain Mumbari (DOD): "Mumbari, Ghislain T  (Yaounde)" <MumbariGT@state.gov>

**Primary ICPI analyst:**  @nmcarloni 
**iSME to cc:**  Smita Ghosh
**Other analysts to cc:** @ikabore 
**Resources/Products**: Link

**Comment by kkale25** [comment]
@nmcarloni can you update this ticket with the latest info?

**Comment by nmcarloni** [comment]
**Complete**: Zone attribute has been created and is working properly in the dossier
**In progress**: I've confirmed PLHIV, TX_CURR_SUBNAT, and TX_CURR values for FY20, FY21, and FY22 with the Cameroon team. They are working on updating the numbers in their datapack. Currently working with Datastrong to ensure everything we need is pulled into the dossier from the Data Pack or from the MER COP dataset and building out visuals to show coverage as requested

**Comment by nmcarloni** [comment]
All pages have been updated to include Zone in the level selector or as a filter, where applicable. Work is ongoing to develop metrics needed for coverage visuals and ensure data is correctly pulling in from the data pack

**Comment by nmcarloni** [comment]
The Datastrong team is updating logic in coverage metrics to ensure visual populates for FY20, FY21, and FY22. Currently FY22 PLHIV numbers are not available in the dossier. This is a known issue and there is a fix, but it has not yet been pushed to prod...timeline for when it will be updated is not known. There are still some discrepancies between what's in the datapack and what's in the dossier, but this may just be a version issue and I'm investigating further to determine the cause of the discrepancies

**Comment by nmcarloni** [comment]
FY22 PLHIV issue has been resolved. Once the team uploads a new version of the data pack, we should be able to see coverage as expected
