### ISSUE TITLE
OVC - FY18 Targets for OVC SERV & Age/Sex Disaggs (prep for disagg tool) - due 2/20

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#14]
Botswana Team needed assistance with verifying USAID IM & Peace Corps FY18 Targets. Posted in new [OVC folder](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FOVC&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D ).

**Comment by shapaklyak** [comment]
Completed.

**Comment by shapaklyak** [comment]
making more of a template for others

**Comment by shapaklyak** [comment]
battery about to go out, no plug where i'm at. please review new file @jb3436 
![image](https://user-images.githubusercontent.com/5234106/36416707-8042f902-1632-11e8-98b6-77717ad3aef3.png)

**Comment by jb3436** [comment]
Before sending this analysis @shapaklyak put together, let's double check all of the datapacks received so far [here on SharePoint ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack%2FSubmitted%20DPs%20for%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

Please go to the datapacks in the above mentioned folder and: 
1) Download the datapacks
2) Review the OVC_SERV targets for "Active and Graduated" - There should be targets for both. 
3) Please check that the graduated targets are approximately the same proportion for the OU you check as the table Katya put together. 
4) Note where graduated is blank or where the proportion is "significantly different" from the previous table * use your judgement about what is "significant."

**End Goal**: Once we have the summary, send around guidance to SI advsors for this week and next week with the table Katya created flagging this datapack check for them. 

I will attempt to add the columns and the tabs to help facilitate doing this quickly.

**Comment by aliyahwakil** [comment]
Received and reviewing.

**Comment by shapaklyak** [comment]
@aliyahwakil see issue #19 for the previously mentioned task.
