### ISSUE TITLE
COP21 DRC Datapack Support

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#141]
**OU**: DRC
**Request**:  DRC team has gotten approval to use program data to set their treatment targets (similar to COP20); currently working to get PLHIV data into datapack and make decisions around modifications to datapack to align with custom S/GAC guidance 
**PPM**: Approved (Michelle Selim from DUIT is PPM) 
**Date Request:** 3/22/21
**Preferred Delivery Date:**  3/23/21 

**Country POCs:**  
- Malaba, Dany (CDC state.gov) <MalabaDK@state.gov>
- Dady, Shirley A (CDC state.gov) <DadySA@state.gov>
- Dennison, David (CDC/DDPHSIS/CGH/DGHT) <epg8@cdc.gov>
- Mulumba, Serge (CDC usaid.gov) <smulumba@usaid.gov>
- Ngalamulume, Rogers Galaxy (CDC/DDPHSIS/CGH/DGHT) <wye3@cdc.gov>

**Primary ICPI analyst:**  @shazadahmed10 
**iSME to cc:**  N/A
**Other analysts to cc:** N/A
**Resources/Products:** Link

**Comment by shazadahmed10** [comment]
Update: POCs reached out to ICPI about validation errors for HTS numbers. Some PSNU/age/sex rows had negative values for HTS_POS stemming from cascade tab. 
The customized TX_CURR growth rates used caused these validation errors.
After talking to ICPI, team submitted help desk ticket for guidance and reached out to PPM for guidance. wanted to know from PPM if exception would be given to keep numbers as they are when they submit DataPack through validation app or if they should redo their numbers to ensure it passes the validation without any errors. The team worries that if they re-calibrate their numbers, the targets will not reflect their program

Next Steps:
-Michelle(PPM) said she will discuss with Chair and get back to team. 
-Datapack help desk said to go ahead and adjust TX_CURR for Fy21 column to make numbers work

**Comment by HoustonJamie** [comment]
@shazadahmed10  @mehtan @jess-stephens: Shazad thanks for providing this update.   Hopefully adjusting Column U (FY21 TX_CURR Target) resolves this DRC issue.  Since they are at lower coverage they likely don't have to worry about HTS_POS issue, that high coverage countries are dealing with.

**Comment by HoustonJamie** [comment]
@shazadahmed10 can this ticket be closed out?
