### ISSUE TITLE
COP21 Rwanda Datapack Support

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#142]
**OU:** Rwanda 
**Request:** Support the use of CLHIV estimates in the datapack and PSNU/IM tab along with support (additional support being provided by S/GAC, details below)
**PPM:** Approved by Sarah Herbst DUIT Liaison 
**Date Request**: 3/31/21
**Preferred Delivery Date:** TBD

**Country POCs:** 
- Hoagland, Alexandra (Kigali) <HoaglandA@state.gov>
- Oluoch, Tom O. (CDC/DDPHSIS/CGH/DGHT); hof0@cdc.gov; 
- Malamba, Samuel Sewava (CDC/DDPHSIS/CGH/DGHT) (CTR) <hlw5@cdc.gov>

**Primary ICPI analyst:**  @randyyee 
**iSME to cc:**  N/A
**Other analysts to cc:** N/A 
**Resources/Products:** Link

**Comment by HoustonJamie** [comment]
***copied from email chain***

**Issue 1**: The assumptions used in Data-Pack to close the assumed gaps based on the current EPP-Spectrum estimated FY22 CLHIV (<15 years) numbers and the associated 90-90-90 targets appear to be too ambitious. Given all our previous efforts to close these gaps, can we now shift our focus to the way we estimate the CLHIV numbers in EPP-Spectrum/Naomi. We strongly believe that the CLHIV (<15 years) national numbers in Spectrum are over-estimated

**HQ Lead**: ICPI @randyyee . Rwanda case-based surveillance has been scaled to most if not all PEPFAR sites in Rwanda (Represents ~60% of the TX_CURR), and includes children. I think the Rwanda CBS data is in column HTS: BB (1,147 new HIV positive kids identified, ~70% in Kigali City; other SNUs are much lower at ~100 <15 total per year), to triangulate 4 data sources, 1) CLHIV spectrum estimates, 2) Family index testing coverage, 3)Case based surveillance, 4) Historical PMTCT coverage over the last 15 years. Demonstration of high family index testing coverage, low numbers of new peds cases, and high historical PMTCT coverage should be documented with targets approved by S/GAC to identify SNUs where PEPFAR peds targets can be lowered.

**Issue 2**: There is a discrepancy between the number of newly identified positives from the 1st 90 estimates (FY22-FY21=217,215-208,411=8,804) and the total number of positives expected to be identified through the listed testing modalities which is only 7,001. How will this difference in positives (8,804-7,001 =1,803) be met?

**Lead**: PRIME/Sara. Will look into this more in the datapack in the coming days. I know the positives in OtherPITC are from the non-PEPFAR funded sites in Kigali--is this being added into the total number of positives expected? We would combine issues 2 and 3 together, since first issue is that it doesn't look like the positives are being added into the total value at the beginning (but we could be wrong here, just a first glance). This needs to be done first in column G (this is a good Scott question, since there may be other unintended impacts there); and then the HTS tab would need to be adjusted from there. Key issue is understanding the total programs HIV case finding and the PEPFAR specific targets and being consistent across the data pack and the MER reporting.

**Issue 3** HTS worksheet: What does ‘HTS_TST_POS difference to be adjusted’ in column BO mean?
With an estimated national HTS_TST_POS of 8804, 7001, 6453 or 5337 and the current national HIV testing yield of 0.4%, a total number of HIV tests needed will range between 1,334,250 and 2,201,000. Data-Pack seems to suggest that 407,864 HIV tests will be done, with 401,411 testing negative, suggesting that 6,453 tests will be positive but HTS_POS for FY22 = 5,337 or 7001 a yield of 1.3% or 1.7% respectively. Is this for PEPFAR only or national). If these are PEPFAR numbers then the contribution of PEPFAR to the HTS_POS numbers will be too high and if these are national estimates, the yield seems to be too high.

We therefore need to be helped to understand the HTS_TST and HTS_TST_POS numbers in the HTS worksheet.

**HQ Lead**: PRIME/Sara. Will investigate with #2 above.

**Issue 4** PEPFAR: The TX_PVLS (D) number (134,132) provided in the Data-Pack is higher than TX_CURR number (132,955). TX_PVLS (D) should be less or equal to TX_CURR 
**HQ Lead**: PRIME/Sara. Not sure what is causing this, best way to investigate is to identify a few rows where column AP > AE and look the columns that are feeding AP to better understand what is driving this. A couple theories 1) Could just be a rounding issue given the numbers are pretty small in all PSNU/age/sex rows but add up across OU, and 2) There are TX_NET_NEW negative FY21 targets in column V (last year’s COP); not sure if this is related or not.

**Issue 5** We also need your help to populate the PSNUxIM worksheet 
**HQ Lead**: ICPI @randyyee

**Comment by randyyee** [comment]
Issue 1: 

- Received requested data sources from country team
- Preliminary analyses shared with HQ 
- HQ discussion: Is the country doing all they can to find CLHIV? (re: index testing cascade)
- Shared analyses and discussion points with country team

Issue 2-4:

- Emails exchanged to troubleshoot datapack challenges and issues
- Datapack review ongoing

**Comment by randyyee** [comment]
Rwanda needs help with HTS tab. They are requesting for a reduction in INDEX contribution from 75% to 60%.

**Comment by randyyee** [comment]
Team submitted and in review
