### ISSUE TITLE
Potential Recurring Request: COP21 HTS Tab Datapack Support 

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#143]
Below is an example of a request we received from Burundi, which is being resolved by the HQ Country Team (no action on ICPI's part for now). We believe this will be a potentially recurring request for other OUs in the near future. Assigning @mehtan and @jess-stephens to work on the issue below and document findings in this ticket so it can be referenced in the future, if need be.

This is not an urgent or time-bound specific OU request. 
----------------------------

**OU:** Burundi 
**Request:** In some PSNU/age/sex combos, HTS_POS other is negative (Cascade, BK) country team trying to fix but not sure what is driving this error 

**PPM:** ICPI playing an advisory role;   (Pooja)  
**Date Request**: 4/7/21
**Preferred Delivery Date:** 

**Country POCs:** 
-Noah Bartlett <nbartlett@usaid.gov>; (AID HQ backfill) 
-Apollinaire Kavungerwa (USAID SI lead) 

**Primary ICPI analyst:**  @mehtan @jess-stephens 
**iSME to cc:**  
**Other analysts to cc:** 
**Resources/Products:** 

On review this issue  driven in high coverage (>95% ART/PLHIV Cascade Y contexts) by 

**1)** Overestimating number of new positives coming from PMTCT, TB and/or VMMC programs (likely explanation is that people are reporting as new positives in these settings even though they are known positives, can be as high as 90% of reported new positives from ANC sites in a high coverage site in Malawi)  
**2)** To correct filer for rows with BK negative, and review (PMTCT, Z), increase from current % up to total positives (NOTE: this is not 100% but from column X to column AE/ column T)  
**3)** you may or may not need to complete a similar approach when reviewing TB_STAT and VMMC_CIRC targets

**Comment by HoustonJamie** [comment]
@mehtan @jess-stephens no specific turn around time, this might be something that would go to talk through on Monday, i have a recent Rwanda datapack that may also be a good one use as well to figure out what an SOP would look like.   Good news; is issue is much easier than last year https://github.com/ICPI/COP/issues/113 since Scott resolved most of this for COP21 but some manual editing may still be needed for the OUs with very high HIV coverage and low prevalence (good problem to have).

**Comment by mehtan** [comment]
Great, thanks Jamie!

**Comment by jess-stephens** [comment]
Hey @HoustonJamie, @mehtan and I worked on the cheat sheet here. We can discuss more in our meeting at 4pm, but let us know if you have any feedback. It's posted in the COP21 Engagements Folder on SharePoint, [here](https://pepfar.sharepoint.com/:w:/r/sites/ICPI/Shared%20Documents/Engagements/2021/COP21/Cheat%20Sheet_%20Testing%20Targets%E2%80%AF.docx?d=wfb62212bfe824342a2c3b28cd1e5178e&csf=1&web=1&e=TpZXK0).

**Comment by HoustonJamie** [comment]
Cheat sheet approved by S/GAC and included in update to datapack user guide (LINK [HERE](https://apps.datim.org/datapack-userguide/05-Cheat_Sheet.html))
