### ISSUE TITLE
COP21 South Sudan Datapack Request

### ISSUE THREAD

**Issue by kkale25** [ICPI/COP18#144]
**OU:**  South Sudan
**Request:** 

1.	Current TX_CURR discussion with OGAC is to keep target at 60,808 though country team feels 54,000 is more realistic. Target in data pack is still 61, 293 as adjusting cascade column Z (Targeted host country ART coverage) and column X  (PEPFAR Coverage of Host Country TX_NET_NEW_SUBNAT (FY22) (%)) has failed to bring target to 60,808. Will need assistance how to bring the target to 60,808.
2.	HTS Tab: Missing values column BN (Final HTS_TST_POS); BT (Total HTS_TST_NEG) and BU (Total HTS_TST) and BV (Aggregate Yield Rate (%)) NEED HELP.
3.	PSNU/IM has no data (Alex Bolo working on this)
4.  TX_NEW target is very low at 7,616 as we are sure the TX_NET New of 26,929 column V (PEPFAR TX_NET_NEW (FY21 Targets) will not be achieved. We tried to adjust column AF (Proportion of TX_NET_NEW from New ART Initiation (FY22) (%) to between 300-600%) by county supported but the changes fail to safe though it takes the target to about 15,000 which is more realistic.

**Zendesk Ticket Number**: The ticket assigned is #39662 
**PPM:** Approved 
**Date Request**: 4/9/20
**Preferred Delivery Date:** 

**Country POCs**
- Alex Bolo 

**OGAC POCs:** 
- Sara Herbst
- Ayibatari Burutolu (PPM)

**Primary ICPI analyst:**  Neha Mehta @mehtan 
**iSME to cc:**  
**Other analysts to cc:** 
**Resources/Products:** Link

**Comment by HoustonJamie** [comment]
@mehtan can you update this ticket?

**Comment by kkale25** [comment]
Hi @mehtan...can you share how this request went and close it out?

**Comment by mehtan** [comment]
Hi! Just waiting to hear if everything went ok with the submission today and will update tomorrow if I don’t hear anything. Sorry for the delay!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mehtan** [comment]
This ticket has now been resolved. South Sudan was able to adapt DP to achieve desired targets and resolve errors with formulas (ie some places were incorrectly hard coded). Yay!
