### ISSUE TITLE
ROP 21 Asia Regional Program SDS Tables 

### ISSUE THREAD

**Issue by jordanadeleon** [ICPI/COP18#145]
OU: Asia Regional Program
Request: Support for the ROP 21 SDS Tables
Pull country-specific tables from Sharepoint 

Dates:
PPM: Approved
Date Request: 4/6/2021
Preferred Delivery Date: 4/20/2021

Country POCs: Kristin Cooney

name
name
Primary ICPI analyst: Jordana De Leon
iSME to cc: Emily Coard
Other analysts to cc: Vishal Jani, Travis Lim, Nicole Zender, Maria Au 
Resources/Products: Link

**Comment by jordanadeleon** [comment]
Update: 1st draft was submitted on 4/24/2021. The Asia Regional Program will send me a new file to update.

**Comment by jordanadeleon** [comment]
2nd draft was submitted on 4/27/2021. Additional graphs for the SDS were submitted on 4/29/2021.

**Comment by kkale25** [comment]
Waiting for FAST to be reflected in the PAW. After this, Jordana will pull figures from PAW and put into SDS for final completion of this request. @jordanadeleon
