### ISSUE TITLE
COP21 Zimbabwe Datapack Support

### ISSUE THREAD

**Issue by kkale25** [ICPI/COP18#147]
**OU**: Zim
**Request**: During the initial data pack review, we have identified some areas within the HTS targets that don’t align with previous discussions on testing strategy. The Zimbabwe team has expressed some challenges working through the validation logic within the data pack to update the testing distribution and have requested assistance from ICPI.
**PPM**: Requested by DUIT Liaison; approved; 
**Date Request**: 4/24/21
**Preferred Delivery Date**: 5/7/21

**Country POCs:** 

**OGAC POCs**:
Wingate, Therese I. (CDC/DDPHSIS/CGH/DGHT) <gza2@cdc.gov>
Cole, Jennifer M ColeJM@state.gov
Zender, Nicole (CDC/DDPHSIS/CGH/DGHT) <qpb5@cdc.gov> 

**Primary ICPI analyst:** @LaChandraS @HoustonJamie 
**iSME to cc:** 
**Other analysts to cc:**
**Resources/Products:**

**Comment by kkale25** [comment]
Potentially the same HTS issues we've run into before that Neha/Jessica supported: (Link [HERE ](https://apps.datim.org/datapack-userguide/05-Cheat_Sheet.html) to the cheatsheet).

Call set up on 4/26 to discuss further.

**Comment by LaChandraS** [comment]
Final datapack submitted
