### ISSUE TITLE
Global HTS Flow Diagram - Mike Grillo

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#15]
***Index Patient Partner Notification Diagram** *

Request from Mike Grillo - Floating HTS lead sitting with Cameroon
Amb. Birx requested this and he is getting in front of request

**Need**: Visual to help OUs conceptualize Index partner notification strategies
Review https://www.pepfarsolutions.org/ for SOPs on testing

**Description of Need**
A few generic flow diagrams looking at patient flow - how does a patient become positive, partner notification, and how you test the partners, facility, community, self test, then each new patient becomes a new index patient. 

One scenario is- you are at the facility - you are a current patient, we dont have any information, you are positive, you ar eon ART, we didn't test your family, kids, bf. Want to test. Go through partner notificaiotn model. At the facility will contact partner. Or you bring your partner in.  Testing with partner - and other partners. Give them self tests. Then confirmatory. 

Or give self test to the positive person and they go home with them

You are positive and my husband is far away - call a community partner in that other village or workplace and test kids and husband and get the results - then if they are positibve - report - assumes a unique identifier and a strong partner notification .. strong interagenyc

Different ways of getting tested

How to document that and the definitions behind that. 

**Different populations**
AGYW
KP
Men

- Include Self Testing
- HTS algorithm - include that
- Community - mobile testing 

Who we count - sexual partners of positives, the children of positive moms, 

Deadline: COB today

**Comment by mehtasp** [comment]
Draft of diagrams have been emailed to Dr. Grillo for review. Awaiting feedback.

**Comment by jb3436** [comment]
Followed up with Dr. Grillo. He has used the diagram to continue conversations with colleagues, but would like to get feedback from USAID and CDC colleagues to contribute to the diagram. We will close this out for now as the presentation to the ambassador that Dr. Grillo would like to do will be post RPM and will likely fall under the cluster activities. 

Most recent draft of the slide deck below and saved [HERE on sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) and snapshot below. 

![image](https://user-images.githubusercontent.com/13006198/36644352-c91c4208-1a26-11e8-89aa-abeedc27bc98.png)

![image](https://user-images.githubusercontent.com/13006198/36644355-d1d4ef6c-1a26-11e8-8852-8ac4391de948.png)

![image](https://user-images.githubusercontent.com/13006198/36644357-dce3a088-1a26-11e8-8771-2c9026d6162d.png)

![image](https://user-images.githubusercontent.com/13006198/36644359-e7541106-1a26-11e8-902c-f8ffe1102a1d.png)

![image](https://user-images.githubusercontent.com/13006198/36644362-f0ac6bcc-1a26-11e8-94c7-e04f98a547e6.png)

**Comment by jb3436** [comment]
Requested these three updates. Shabeen would like to share with the SI advisors. Shaylee will make the updates. 

Follow Up:
1. Change the first page to include who we're targeting for index testing (sexual partners of male PLHIV, sexual partners and children female PLHIV). 
2. Include one more intro slide that summarizes the options - ways to help a patient disclose versus options that don't require disclosure. 
3. Throughout the model, add the option for couples counseling and testing (PLHIV pretends they don't know their status) and also self-testing and then add model slides at the end that describe each of ‎those.

**Comment by jb3436** [comment]
Mike will set up a meeting with the SI advisors to walk them through the infographic since it will not be cleared in time. Once the above comments are incorporated and sent to Mike, we will close the ticket. @mehtasp

**Comment by mehtasp** [comment]
Version 3 posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence) . Closing ticket and will follow-up with Mike for further comments/suggestions.
