### ISSUE TITLE
OVC Program Status by OU (FY17 APR and FY18 Targets)

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#19]
Providing proportions for all OUs for OVC Active and Graduated for targeting setting, re: issues identified in #13 .

**Comment by shapaklyak** [comment]
Just posted Tableau and PDF files titled "OVC SERV Program Status by OU FY17APR and FY18 Targets" on [pepfar.net](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FOVC&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
Emailed only SI advisors who had issues in the list referenced above based on Irum's go-ahead. Want to make sure that OUs set targets for both Active and Graduated. Use percentage of graduated from previous performance to target for FY19 as a base. Most have set graduated targets between 3-5%.

**Comment by shapaklyak** [comment]
From @jb3436 
@aliyahwakil 

Due by COB today 2/20
LOE - Maybe 1 hour

Before sending this analysis @shapaklyak put together, let's double check all of the datapacks received so far [here on SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FOVC&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Please go to the datapacks in the above mentioned folder and:
1) Download the datapacks
2) Review the OVC_SERV targets for "Active and Graduated" - There should be targets for both.
3)Please check that the graduated targets are approximately the same proportion for the OU you check as the table Katya put together.
4) Note where graduated is blank or where the proportion is "significantly different" from the previous table * use your judgement about what is "significant."

**End Goal**: Once we have the summary, send around guidance to SI advsors for this week and next week with the table Katya created flagging this datapack check for them.

I will attempt to add the columns and the tabs to help facilitate doing this quickly.

**Comment by aliyahwakil** [comment]
Received

**Comment by shapaklyak** [comment]
@erinschelar  fyi

**Comment by erinschelar** [comment]
Following up about  the comment to "Use percentage of graduated from previous performance to target for FY19." Is previous performance a starting point that can be changed, or is this now required guidance? The user manual indicates that this is an assumption that can be changed and that would make most sense programmatically.

**Comment by erinschelar** [comment]
@jb3436 Can you please forward email that was sent to SI advisors regarding the OVC_SERV targets?

**Comment by aliyahwakil** [comment]
I reviewed proportions for OVC_SERV FY18 targets and did not find any significant differences between proportions in submitted data packs (Zambia, Lesotho, Zim, Botswana, DRC, Namibia, Uganda, Nigeria, South Sudan) and Katya's table. All Datapacks I reviewed reported "Graduated"

**Should I also note  whether "Active" were blank or not?**

Zambia has two Datapack files uploaded to sharepoint, I checked both and both are OK. 

I noticed that Lesotho Graduated was not reported on Katya's table but I'm assuming that's because the proportion was so small (0.0003).

**Comment by shapaklyak** [comment]
@aliyahwakil could you please compare the proportions for OVC_SERV FY19 Targets in the datapacks to the FY18 Targets in the other file posted? slack me and/or @jb3436  for q's

**Comment by aliyahwakil** [comment]
I posted the findings to sharepoint within the [Viz > OVC folder](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/OVC). File name is OVC SERV Program Status FY18 Targets and FY19 Targets by OU_20180220. I highlighted in RED significant differences. 

Took about 40 min to review.

**Comment by jb3436** [comment]
@erinschelar , no email was sent to SI advisors - we are doing this to flag issues before communicating with them. The original plan was to show them their previous performance to assist them in setting their targets for graduated because a few countries only set targets for active. Before sending out a blanket email, we wanted to check what was done and if it looked similar to their previous performance.

**Comment by jb3436** [comment]
Based on the results of Aliyah's analysis - Two countries have not yet set both active and graduated program status targets in the submitted datapacks (Botswana and Nigeria) And Zambia set very high graduated targets compared to their previous performance. We will notify the three implicated SI advisors.
