### ISSUE TITLE
2nd 95 Check

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#20]
Request from I.Zaidi to look at ART Coverage rates against disease burden. We will be doing this for the 13 priority countries that are here this week. In order to do this, we need to pull the following columns from the Data Pack to calculate burden. 

Data Packs are available from [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack%2FSubmitted%20DPs%20for%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

- Botswana
- Lesotho
- Namibia
- Swaziland
- Uganda
- Zambia
- Zimbabwe

A | B | C | D | E | F | G | H
-- | -- | -- | -- | -- | -- | -- | --
Operating Unt | PSNU | SNU Priority | Estimated Number of PLHIV, end of   FY19 | FY18 Expected TX_CURR Result | Estimated Current on ART, end of   FY18 | FY19 Target ART Coverage Rate | Unmet Need
  | [Assumption Input!C:C] | [Assumption Input!D:D] | [Assumption Input!H:H] | [Target Calculation!AB:AB] | [Assumption Input!M:M] | [Assumption Input!W:W] | =D3-MAX(E3:G3)

**Comment by jb3436** [comment]
Assigned to Dustyn. and @HoustonJamie is QCing

**Comment by kschlenker** [comment]
Dustyn - Uganda has an unclustered datapack but actually reviews & targets coverage data by clusters. Let me know if you have questions about their datapack & coverage rates

**Comment by dp1984** [comment]
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Datapack/2nd%2095%20Check.xlsx
