### ISSUE TITLE
Allocation by SNUxIM total check - Due COB today 2/20

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#21]
We need to provide country teams with a check for the Allocation by SNUxIM tab. 

The solution is to provide each team with sheet that has 3 rows - (a) target name, (b) SNU Target Total, and c) Allocation by SNUxIM.

Go into the SNU Target tab and pull the Target headers and Total Row (4:5) for all the columns of target data (F4:DN7). Paste this into a worksheet.

Go to the Allocation by SNUxIM tab and copy the total row for all targets (DP5:HX5) and paste this in the row below the SNU Target totals.

Add conditional formatting to highlight Allocation by SNUxIM totals that do not match the SNU targets. (=ROUND(A$2,0)<>ROUND(A$3,0).

Repeat for all countries we have Data Packs collected for, which can be found on [PEPFAR SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack%2FSubmitted%20DPs%20for%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence).
- [x] Botswana (received)
- [ ]  Cameroon
- [x] DRC (received)
- [x] Lesotho (received)
- [x] Namibia (received)
- [x] Nigeria (received)
- [x] South Sudan (received)
- [ ] Swaziland
- [x] Uganda (received)
- [x] Zambia (received)
- [x] Zimbabwe (received)

**Comment by jb3436** [comment]
@pvinayak001 suggested summarizing what the common issues are based on the checks above. Based on the report out/results of your checks above, Pooja will draft an email with guidance on what to avoid across countries and what countries can do next week to avoid these issues. @HoustonJamie , anything else to add?

**Comment by KTmonkey** [comment]
My first task!!

Questions/clarifications - 
1) when is this due?  
2) is there a preferred order in which I go thru the countries; prioritization? 
3) Can I put my comments in one document or does each country need their own?
4) Who do I notify of it's completion? Jasmine, Jamie, Aaron, Pooja, Admin? 
5) I'm looking in the pepfar.net link provided in the original post and I see Zambia's disagg tool is in there, can I ignore this? Is this task only on the regular datapacks or the disagg tools as well?

**Comment by jb3436** [comment]
Due by COB today. The LOE should be ~2 hours (including downloading, doing above, summarizing, posting summary to GH and output to SharePoint). @achafetz - do you think that is fair or way over/under?

**Comment by achafetz** [comment]
very low workload. It shouldn't take more than an hour, hour and a half max.

I would say one file with multiple sheets, one for each OU. We can decide how to distribute in the am.

Data Pack has all the info you need. Disagg Tool does not

**Comment by KTmonkey** [comment]
Point of clarification, in the original request, should this say  DN5 or DN7?

_Go into the SNU Target tab and pull the Target headers and Total Row (4:5) for all the columns of target data (F4:**DN7**). Paste this into a worksheet._

**Comment by KTmonkey** [comment]
Hi friends, 

this will probably be very helpful for the country teams. LOTS of discrepancies. I'll summarize the best I can but lots of discrepancies. 

High five for Nigeria!! NO DISCREPANCIES! Botswana, and Uganda only a few discrepancies!

Overall - Treatment, PMTCT and HTS seem to be the most fraught with issues, OVC, KP, VMMC, PP_PREV tend to do much better in terms of proportion of matching. 

Eyeballing the numbers, sure some are off by just one which is probably just a rounding issue or maybe someone had a mistake when typing, ex South Sudan in my document col F (T_tx_new_fy19) - 17,0## vs 17,0##

 but MANY are off by a lot, ex South Sudan, Col CE in the document I made (T_vmmc_Circ_FY19) is 0 in one tab and 1,### in the other. 

Sorry I can't really give you a better summary of things to look out for, it's a bit all over the place.
Let me know if you need anything else. 

Completed: 2/20/2018 @ 2:09pm EST
LOE 1.5 hrs

Doc uploaded here: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by KTmonkey** [comment]
I tried to check the boxes in the original post to indicate that I completed all the countries that we had datapacks for but I'm not sure if that saved. Apologies if those aren't checked.

**Comment by KTmonkey** [comment]
from @HoustonJamie 's  email 2/20 at 4:40pm:

I added a few rows to contextualize and set a arbitrary +/-5 % cut off that I think the SI advisors used last year in the target review tools.  In summary 
 
Dark Green: Nigeria (no mismatch)
Light Green: Bots, Nambia, Ug, Zambia, Zim (only a few areas, TB/HIV, OVC seem to more common than others
Yellow: DRC and South Sudan (I think they haven’t de-duplicated yet, but I might be misreading this, should double check in the AM)
Red: Lesotho (but caveat here is they were told to set PEPFAR=National targets, but not sure this can explain the mismatches being seen) 

For some reason Community Testing target are the most consistent gap so I think it was unfortunate that Pooja and I started with that one and the testing disag tool is the most complicated and critical piece of the puzzle for target setting this year, but good to know it was an outlier.

Jamie's version of the document is on sharepoint @ - 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by pvinayak001** [comment]
THanks @KTmonkey ! Summary of issues sent out to SI advisors today along with validation file. They are finding it helpful. Caveat to note: Per DOD guidance, DOD targets are included in the Allocation by SNU x IM tab, but not the SNU targets tab. So those will contribute to the discrepancy as well. 

@achafetz is writing up guidance on how to do the check automatically within the tool, but we may get some requests to re-run the checks based on data pack changes that were made today.

**Comment by KTmonkey** [comment]
I am at your disposal, just let me know when you need me.

It's always the military...

**Comment by achafetz** [comment]
update [Change Log](https://github.com/achafetz/DataPack/wiki/COP18-Data-Pack-Change-Log), 23, with how to add this to the DP

**Comment by pvinayak001** [comment]
@achafetz Can you confirm this is NOT considered a structural change for consideration by systems team since it is only adding a row?

**Comment by jb3436** [comment]
Since this is for RPM one and these are done I am closing this out.
