### ISSUE TITLE
Haiti site X partner analysis support

### ISSUE THREAD

**Issue by KTmonkey** [ICPI/COP18#23]
Catherine Nichols (cnichols@usaid.gov) is supporting the Haiti team for RPM 

Request for an analysis for PEPFAR Haiti: a site-level analysis ranking sites by 8 metrics on the clinical cascade.  We are conducting the analysis by the following populations: all, Females 15+, Males 15+, Peds <15, AGYW, OVC, KP.

**Comment by KTmonkey** [comment]
@cnichols3h has been working on this and needed help QCing what she already had put together. She and I spent about 45min using Panorama to QC some of the site X partner TX_CURR and HTS_TST <15 Female numbers this evening. 

Anticipate there being a need for additional QC support as well as support in combining two of the excel files she is working with.

**Comment by jb3436** [comment]
Thanks! @KTmonkey and @cnichols3h , would you kindly upload a draft version to sharepoint so we can see what the analysis looks like?

**Comment by cnichols3h** [comment]
Yes - I am happy to do this.  Is there a suggested place where I should post this on sharepoint?  (ie. draft of an analysis)

**Comment by KTmonkey** [comment]
@cnichols3h I emailed you the link this am

**Comment by jb3436** [comment]
@cnichols3h anywhere in the RPM Folder [here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)would be good. It is where we are tracking all of the COP support. Thanks!

**Comment by cnichols3h** [comment]
@KTmonkey @jb3436 thank you!  I created a Haiti folder under Visualizations and uploaded the site-level version....still working to add a partner-level view.

**Comment by cnichols3h** [comment]
@jb3436 @hessionra - I am requesting help on this project.  Specifically, need another analyst to help me pull Haiti site level data AND partner BY population for a list of FY17 MER indicators.  I can work w/ this person directly w/ more of the details.  Thanks.

**Comment by mehtasp** [comment]
Hey @cnichols3h I'm around to help. Let me know what you need

**Comment by cnichols3h** [comment]
@mehtasp - awesome - thanks!  i will send you an email shortly to explain further & see what you think.

**Comment by KTmonkey** [comment]
I’m here too! Let me know what you need!


________________________________

**Comment by shapaklyak** [comment]
@cnichols3h how are you doing on this? do you need any further help or is this completed?

**Comment by cnichols3h** [comment]
@shapaklyak @KTmonkey - thank you!  this is completed.  @mehtasp helped me out.  i actually have a new request for haiti.  i will start a new ticket now to see if anyone in DC can support.

**Comment by shapaklyak** [comment]
@cnichols3h ok great. can you post a link to the completed deliverable here (linked to pepfar.net) and close out this issue. 

Thanks!

**Comment by cnichols3h** [comment]
@shapaklyak - I will do that.  Thanks!

**Comment by MicSherlock** [comment]
Hi all, I was just taking a look at this and noticed an error in the calculation of Tx_Net_New. its using Tx_New instead of Tx_Curr. 

The equation should as follows: 
Tx_Net_New_R (FY17) = Tx_Curr_R (FY17) - Tx_Curr_R(FY16)  or 18Q1 = Tx_Curr_R (18Q1) - Tx_Curr_R(FY17)
Tx_Net_New_T (current period) = Tx_Curr_T (FY18) - Tx_Curr_R (FY17)

**Comment by cnichols3h** [comment]
@MicSherlock thanks!  I will fix.

**Comment by mehtasp** [comment]
Posted the population file [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHaiti&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)
