### ISSUE TITLE
S.Sudan Rasta Table Request - Due by 2/22 COB

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#24]
Request from HQ SI advisor Ta'Tyana and In country SI Alex B.
Approved by ICPI
Due by 2/22 COB

Purpose: Ambassador presentation
Reason: Lack of time/staff

Rasta tables by SNU as seen in example below, for Scale-up aggressive (n=6 including Mil) and Sustained SNU’s (n=11). South Sudan expects to run the disagg tools today. 

![image](https://user-images.githubusercontent.com/13006198/36468495-978c40ee-16b1-11e8-886a-0e567bd7a4c0.png)

**Comment by jb3436** [comment]
Shazad and Jamie met with Tat'Yana - 
There is a copy/paste error in their testing disaggs intheir datapack

Tat'Yana:
- Will compare the yields in pano to datapack 
- Will replicate SNU x IM changes in the disagg tool
- report back on data to use
FYI - There are no completeness issues with age/sex completeness. 

Tat'Yana reported back on the yields. @shazadahmed10 Will use the factview file for FY17 Q2,3,4 and will sum them up, no clustering and will send that in the am. Not using Q1 because of a massive testing campaign that always happens that dilutes the yield.

**Comment by mehtasp** [comment]
Sent Tay'Yana the product referenced in ticket 10. She will use that in any of her analyses. Closing ticket.
