### ISSUE TITLE
Global: OU level HTS_TST for other PITC modality

### ISSUE THREAD

**Issue by jaliasd** [ICPI/COP18#26]
Walk up: Irum requested a table looking at HTS_TST for Other PITC by OU, results and targets. There are no targets by modality for FY17

**Comment by jb3436** [comment]
@jaliasd , connect with @shazadahmed10 and @imujawar to see if what he has put together for Issue #10 and #11

**Comment by jb3436** [comment]
@jaliasd will send final product to Irum for next week's OUs.
