### ISSUE TITLE
UNAIDS Spectrum TX to PEPFAR comparison at OU and SNU level

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#27]
Requested by Irum
Approved by ICPI

**Purpose**:  OGAC has provided guidance that country teams should consider 'correcting' or adjusting the ART inputs to SPECTRUM - for DQA or PHIA results, under selected circumstances.  DRC and Lesotho approached ICPI about providing support for advice on adjusting their data pack based on adjustments to their SPECTRUM models and their PHIA results. 

**Task 1** (@dp1984 ):  Created PSNU, FY18/FY17, TX_CURR file with age/sex and Total Numerator (from Standardized Disag, No Numerator in FV for Disaggregate

**Task 2** (@dp1984 : Create pivot and copy into UNAIDS Spectrum output table for comparison CY PEPFAR TX_CURR totals 15+ M, 15+ W, and <15 
 
**Task 3**  (@jaliasd @jb3436): Meet with Mary, Lesotho, Swazi and Uganda to draft checklist for SI advisors to confirm that adjustment has been completed.  A check list for SI advisors to catalogue steps/methods/data sources for calibrating spectrum estimates and district disags for PLHIV estimates.

**Comment by dp1984** [comment]
spreadsheet located here: 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Treatment/UNAIDS%20Spectrum%20TX%20to%20PEPFAR%20comparison%20at%20OU%20and%20SNU%20level.xlsx

**Comment by jb3436** [comment]
Had meeting to brainstorm checklist: In attendance, reps from SPECTRUM, PHIA,  ICPI, Swaziland, Lesotho, and Nigeria. 

**Next steps**:
1. Jasmine synthesizing notes and sending to @HoustonJamie  
2. @HoustonJamie will distill the primary points from the notes into guidance for country teams. 
3. Send to Irum for distribution

Note: Given the timing, this will be more usefull for week 2 countries.

**Comment by jb3436** [comment]
**Follow Up**

1. Jasmine synthesized notes and sent to Jamie and Josh
2. Jamie distilled primary points into guidance for country teams to use as a sort of qualitative interview to determine what process was taken and what inputs are appropriate. 

**Outstanding**: 
1. Finalize guidance
2. Send to Irum for distribution

**Comment by HoustonJamie** [comment]
Handed off notes to Laura for finalization
