### ISSUE TITLE
Botswana FY18 Targets - Due COB 2/21/2018

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#30]
Team Botswana needs FY18 Targets OU x IM for the following indicators. This was through Amy Gottlieb and Sega (USAID) for comparison of FY18 targets to FY19 datapack (in current working version) to prep for any questions/comparisons.  

Quick table of OU x IM is sufficient organized by OU, IM, IM #, FY18 Targets. 

- pp_prev (katya + kimi)
- ovc_serv (katya + kimi)
- hts test
- hts pos 
- tx new
- tx curr

**Comment by shapaklyak** [comment]
Thanks @shazadahmed10 & @kimisatoPC ! 

Completed!

Consolidated file posted on pepfar.net in [Botswana folder](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by shapaklyak** [comment]
@shazadahmed10 can you do the same for HTS by Modality? per email from Amy Gottlieb (below)

![image](https://user-images.githubusercontent.com/5234106/36487111-cad89ca0-1728-11e8-966a-00c654cd8d8a.png)

**Comment by shazadahmed10** [comment]
emailed to Katya

**Comment by shapaklyak** [comment]
Thanks @shazadahmed10 ! emailed to Sega & Amy Gottlieb of Botswana team this week.

**Comment by shapaklyak** [comment]
asked for HTS TST POS by Modality, sent and file posted on pepfar.net in [Botswana folder ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by shapaklyak** [comment]
Botswana FY18 Targets for OVC SERV + OVC_HIV STAT now requested by IM. Completed by @mehtasp & I

**Comment by mehtasp** [comment]
Botswana OVC FY18 Targets posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)
