### ISSUE TITLE
Lesotho - DATIM SNU/IM Tab 

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#31]
Purpose:  Lesotho scored a 50% on SNU/IM tab datapack check. SI advisor asked for support for country SI team to update 

Task1:  @pvinayak001 Support country team to add missing PSNUs (4 out of 10), and allocate targets to IMs for indicators

**Comment by achafetz** [comment]
@pvinayak001 and I met this afternoon. We walked through the process and shouldn't be too bad. 

@jb3436 or @HoustonJamie, before she can start, we need to get the full list of new mechanism and DSD/TA to add by PSNU for @pvinayak001 to add in.

table as follows

Dsnulist | D_priority | D_mech | D_type
-- | -- | -- | --
_Military Democratic Republic of the   Congo | Mil | TBD1 | DSD
[necessary] | [necessary] | [necessary]

**Comment by pvinayak001** [comment]
I met with Ian and Sadhna this evening. Ian still needs to get the district x IM info from program people. I sent him a simplified table that he can send out to program to collect the allocations, and I'll help him consolidate the files into the master datapack (ideally tomorrow morning but whenever we get the results). Confirmed with Sadha that this works for her timeline.

**Comment by Yabayabadoo** [comment]
@HoustonJamie @pvinayak001 A note that the prevention targets have not been finalized. Unsure what the program people will be using to determine allocations, particularly without the comparison to other IMs within a PSNU.

**Comment by jb3436** [comment]
Closing this issue as there is another open issue for Lesotho that is a follow on to this ticket #55
