### ISSUE TITLE
Nigeria disag tool request

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#32]
Requestor:  Roha

Purpose: sit down with Nigeria team who has completed the SNU/IM tab of datapack and populated the disag tool to understand why they are getting errors.

**Comment by achafetz** [comment]
met w/ Otse at the end of the day. clarified issues. 

One big take away was that we need to really make clear that any new SNUxIM pairing in the Data Pack must be added to all the necessary tabs in the Disagg Tools.

Otse may follow up tomorrow AM
