### ISSUE TITLE
DRC - DataPack Updates: Github Corrections #17-19

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#35]
From SI Advisor: Leigh
Approved by ICPI
Assigned to @pvinayak001 

**Request**: The DRC datapack has been updated with the GitHub corrections 17-19. can the ICPI help with this?

**Previous comms**:
Thanks for pointing out the additional caveat around DOD targets. Please continue to follow the guidance provided by DOD on target setting. If you would like to discuss additional checks that could take this discrepancy into account, please stop by the ICPI table on the second floor.

**Comment by achafetz** [comment]
Met with L.Tally. 17 and 19 only apply to DPs with hierarchy changed (the ones populated on Feb13-15). She doesn't need any assistance on this
