### ISSUE TITLE
Nigeria - Disagg tool errors

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#36]
Request from SI advisor - Roha
Approved by ICPI
Assigned to @HoustonJamie , @achafetz @pvinayak001 

There are errors occurring in each tab and it is unclear what the source of the error is. Need a walkthrough of the tool. 

Updates: 

Met with Otse and resolved issues. Team is close to being done with their disagg tool. 

@HoustonJamie @achafetz @pvinayak001 can provide additional comments on how the issue was resolved. Feel free to close the ticket after the update.

**Comment by achafetz** [comment]
Duplicates #32. I believe this should be closed, but will check back this morning. They needed to update with both [Change Log 22](https://github.com/achafetz/DataPack/wiki/COP18-Data-Pack-Change-Log) and [Disagg Change Log 1+ 2](https://github.com/achafetz/DataPack/wiki/COP18-Disagg-Tool-Change-Log)

**Comment by achafetz** [comment]
Only other issue was that their OVC wasn't fully allocated. This problem derived from the fact that the had not added the new mechanism to their OVC (or any) tab.

**Comment by pvinayak001** [comment]
Additional support requested via DATIM support:

a. The numerator total for all the indicators (except OVC_SERV) in the “Allocation by SNUxIM” tab does not match with the disaggregated totals in the indicator tabs. We think that not all the IMs are being pulled from the Allocation by SNUxIM tab to the indicator tabs (similar to the OVC_SERV issue stated above but wanted to flag this to you/ICPI for resolution).

Resolution - Ensure that all added IMs on each tab are fully allocated. From a brief review, it seems there are many IMs that do not have targets allocated, and among those that have allocations, age/sex disaggregates do not always add up to 100%.


b. Identified value errors in the TX_NEW tab of the Disaggregation tool and the following modalities in the HTS Disagg tool - OtherMod, Index, STI, Inpat, Emergency, Pediatric services and Malnutrition. This might be resolved by using the IFERROR command but we thought to flag this to you and the systems team for resolution.

Resolution - Datapack Change Log Fix 22
