### ISSUE TITLE
Global: RPM Resources for Country Teams

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#37]
Requested by Irum/Jasmine
Approved by ICPI
Assigned to @hessionra to complete and coordinate
End product: flow chart/infographic with hyperlinks

**Background**: 
Based on what we are seeing at RPM and a discussion with Irum, it appears there is a need for communication about resources. 

**Issue**: many country teams are creating task teams to build visualizations from scratch, which is not the most efficient use of time. Solution is to use existing visuals and modify them. 

Using the Vision template in the sharepoint folder, use the population focus of the slides and agenda to create a flow that starts with the type of product someone was trying to create.

**Examples** 
Creating OVC visuals --> 
- go to the OVC dashboard - you can modify pivots or visuals 
- go to panorama for some visuals, but it is not available for Q1

Reviewing SIMS -->
- RPM SIMS Cheat Sheet
- SIMS Interagency Dashboard
- Panorama

Creating Clinical Cascade Slides-->

Creating Slide 20 --> use this template or email for help

Analyzing high volume sites

**Comment by hessionra** [comment]
ICPI Product Flow Chart for RPMs can now be found on SharePoint:

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FBest%20Practices&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence
