### ISSUE TITLE
Botswana site level analysis

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/COP18#38]
Purpose: Amb B requested CDC look at the BCPP ART trend data and compare to site level program data because of a recent DQA which showed a substantial overcount in the assessed ART sites.  

Task 1:  @pvinayak001 was the MOH alignment activity completed for Botswana, is that data available in DATIM?  If so can we make this available to country team? if not, no further action 

Task 2:  @imujawar can we pull the SITE/IM FV results, and set up a pivot to let the team review trends in TX_NEW, TX_NETNEW, TX_RET, and TX_CURR for all PEPFAR sites vs BCPP sites (CDC ATL working on producing the comparison file from BCPP) 

@achafetz @jb3436  i think maybe this message was delayed and might be overlapping with what Jason Roff was already doing yesterday.  Do you know if Task 2 has already been completed?  

Deadline not clear, but would be ideal to give an update on LOE and most realistic options by 10.  Thanks!

**Comment by achafetz** [comment]
@imujawar, FY18Q1 site IM are up as of last night on [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FICPI%20Data%20Store%2FMER%2FICPI%20Fact%20View%20-%20Feb%2E%2015%2C%202018%20%28Initial%20FY18Q1%20Data%29%2FSite%20Level&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D) so this should be a straight forward task of subsetting the dataset.

**Comment by pvinayak001** [comment]
Botswana has not submitted MOH Alignment data.

**Comment by imujawar** [comment]
Posted tool on [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Botswana). File name: **Bots_TX_trends_20180221.xlsx**

**Comment by imujawar** [comment]
[R  code](https://github.com/ICPI/COP18/blob/master/Botswana_TX_trends.R) for data manipulation also posted for reference.

**Comment by HoustonJamie** [comment]
Received MOH site data from CDC team in country, merged w 15 sites from BCPP and compared TX CURR at site level. Added narrative from county team and handed off at 6 pm on 2/22
