### ISSUE TITLE
Botswana - map request linkage to treatment

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#39]
Background: Botswana Chair - Melissa Moore would like to see a map for Friday's outbrief displaying the linkages by district, and explore the sociobasis of communities and how it effects linkage. 

Purpose: To identify if PEPFAR should be targeting hot spots and strategize focus on areas for linkage.

Request: Map linkage to treatment by District (PSNU). 

Due: COB 2/22/2018 for Friday outbrief

**Comment by shapaklyak** [comment]
update: @dp1984 & i spoke w/team and waiting to see if they have the internal dataset re: why individuals were not linked to treatment.

**Comment by dp1984** [comment]
Katya & I just discussed this mapping request with Melissa, she's going to get back with us to see if this data may be available as well as some clarifying details.

**Comment by dp1984** [comment]
I'm also going to reach out to Jim Tobias who recently completed a TDY to Botswana to help generate COP visuals to see if he has any relevant maps.

**Comment by shapaklyak** [comment]
Team wants to see this data overlayed with linkage to treatment, however it seems unlikely the team will be able to pull together this data for RPMs, but perhaps for next quarter would be useful to see. 

will keep this issue updated if any changes.

![image](https://user-images.githubusercontent.com/5234106/36529754-f012b868-17c1-11e8-9740-194ee60ba53d.png)

**Comment by shapaklyak** [comment]
FYI - doesn't look like the team is going to have the data to turn this into a map. Hold off for now. Will probably close ticket out tomorrow.

**Comment by jb3436** [comment]
This is transitioning over to GIS workstream workplan @dp1984 and @gsarfaty
