### ISSUE TITLE
Burundi Visualization Request 02152018

### ISSUE THREAD

**Issue by ICPIadmin** [ICPI/COP18#4]
Yesenia Saulino (SI Advisor Burundi) emailed ICPI on 2/15 requesting assistance in generating sample visuals from the RPM COP18 Vision template. She is asking for the visuals **by 2/22**.

For the template visuals and PPT, please see [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBurundi&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D
):

**Comment by shazadahmed10** [comment]
I am taking on the Burundi request, will have it completed by the 2/22 request date

**Comment by mehtasp** [comment]
Emailed Yesenia the FY17 visuals for Burundi (SitexIM Factview file v2_1) using Shazad's SSudan file as a template.

**Comment by mehtasp** [comment]
Uploaded file to sharepoint [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBurundi&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence):

**Comment by mehtasp** [comment]
Addressed Yesenia's concerns and made the fix to the TX_CURR Growth graph by adding a SNU filter (one partner had too many sites and excel didn't like that). Resent and reposted to sharepoint here:
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBurundi&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence
