### ISSUE TITLE
Botswana map request (from Chair) - Investments vs. acheivements

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#40]
Background: Botswana Chair - Melissa Moore - would like to see financial investments vs. successes. What has been planned and what has been historically achieved by district. She would like to see this in a layered map as possible.

Details for analysis: Layered map if possible

- Investment $ by district/PSNU (FAST)
- Breakout the district - show the breakdown of program areas by # program areas and type
- FY18 Q1 results  and then another set with FY17 APR 

Let me know if any questions. Not urgent - after RPM.

**Comment by dp1984** [comment]
from discussions with the FAST team, @HoustonJamie & @jb3436 , I don't believe we can map this information with the data we have available at HQ. However, we could pose this question to country teams to incl. in a future analysis w/ HQ support as this may require triangulation of budget/mer data and detailed understanding of partner rationalization. 

Let's discuss further next steps.

**Comment by jb3436** [comment]
@dp1984 - if you want to write up what the parameters would need to be for this analysis to be done, that could be part of the guidance the GIS team can distribute to country teams. @gsarfaty @HoustonJamie @jaliasd @abrahamagedewICPI , what do you think?

**Comment by abeagedew** [comment]
@jb3436 @dp1984, do the FAST tool and MER have common org hierarchies? I think it would be ideal if we can simply triangulate by the org hierarchy and generate the maps.

**Comment by gsarfaty** [comment]
@abrahamagedewICPI my understanding is that fast does not actually have true geography and instead is reported against snu prioritization categories.

**Comment by HoustonJamie** [comment]
Thanks Abe, but the Fast tool is only at Ou/IM level so no hierarchy unless you know which IMs are in which SNUs

Sent from my iPhone

On Feb 22, 2018, at 10:25 PM, Abraham Agedew <notifications@github.com<mailto:notifications@github.com>> wrote:


@jb3436<https://github.com/jb3436> @dp1984<https://github.com/dp1984>, do the FAST tool and MER have common org hierarchies? I think it would be ideal if we can simply triangulate by the org hierarchy and generate the maps.

**Comment by kschlenker** [comment]
@abrahamagedewICPI I think @gsarfaty is correct. It is made even more complicated because I believe you can list multiple prioritizations on a single line for an investment (e.g., Scale Up Aggressive & Sustained)

**Comment by HoustonJamie** [comment]
Gina ours emails crossed but yep you are correct

Sent from my iPhone

On Feb 22, 2018, at 10:36 PM, gsarfaty <notifications@github.com<mailto:notifications@github.com>> wrote:


@abrahamagedewICPI<https://github.com/abrahamagedewicpi> my understanding is that fast does not actually have true geography and instead is reported against snu prioritization categories.

**Comment by abeagedew** [comment]
Thanks @kschlenker @gsarfaty @HoustonJamie, I was just thinking through the best approach to create these maps. Possibly we can use the prioritizations but as @kschlenker, it will make it a bit complicated if there are multiple prioritizations for a single investment.

**Comment by shapaklyak** [comment]
hi all! this was a wish list request by the chair (not necessarily urgent for RPMs), and @jb3436 and i discussed w/her that it may need more thinking around this type of request. However, if we could put it together sometime in the future, that would be awesome :) if you have other more urgent priorities, i would focus on those but could still explore this idea. @jb3436 what do you think?

**Comment by jb3436** [comment]
Closing htis as this is a longer term project and will transition to the GIS workstream workplan @dp1984 @gsarfaty
