### ISSUE TITLE
Botswana Case Identification among men

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#43]
Team wants to create 2 slides for outbrief:
Case identification among adult men in facility settings (APR17 and FY18 Q1). We trying to show performance in meeting this population.  Including the targets and where they are identified would be helpful.

@shazadahmed10 emailing link to FY17 visuals

**Comment by shapaklyak** [comment]
@shazadahmed10 & I sat together in Botswana room.

Template posted to pepfar.net titled Botswana Index Testing table 18Q1&17" [Visualizations --> HTS](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) 

See **Charts** tab for template for data needed for OU level data FY17APR and FY18 Q1:

- Males
- Females 15+
- Children Under 15
- AGYW 15-24
- Key Populations

**Comment by shazadahmed10** [comment]
Sent to Katya

File on sharepoint: 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Botswana/17%20%26%2018q1%20HTS%20index%20case%20finding%20tables.xlsx
