### ISSUE TITLE
DRC - Age/Sex by SNU Planning Support

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#46]
Request from SI advisor - Leigh
Approved by ICPI
Assigned to Imran @imujawar 

Background: Need assistance with age/sex by SNU breakdown in order to eventually compile the rasta table. 
Similar to request from S.Sudan and Botswana. 

Imran and Jamie meeting with Leigh to discuss details. Will provide more context on the request, what can be leveraged and when it will be completed.

**Comment by imujawar** [comment]
- Merged the two excel files provided, and referenced data in them for final tool. 
- Built reference tables for final Rasta tables (separate table for each SNU1), showing periodic trends for each gender, by Fine age bands. Did not copy paste any of the data provided, but created references, allowing for edits to the original data in the tool. 
- Tool posted on [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Ad-Hoc%20Analysis).
