### ISSUE TITLE
Botswana QC - HTS POS by population 

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#47]
Amy (USAID) South Africa region created the chart linked [here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2fOGAC%2dHQ%2ficpi%2fShared%20Documents%2fCOP%20Support%2fCOP18%2fSupport%20Requests%20and%20Tracker%2fVisualizations%2fBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A)

Please QC these values. 
Due: 2/22/2018-  4pm if possible
File: 
![image](https://user-images.githubusercontent.com/5234106/36539358-3a93d4cc-17df-11e8-99a2-7a11a81506a4.png)

**Comment by dp1984** [comment]
all the other figures add up in pano, however , fy18 q1 results for children doesn't seem to be lining up

**Comment by shapaklyak** [comment]
thanks @dp1984 , i've informed Amy and will keep you posted if there is a further need

**Comment by jb3436** [comment]
QC Complete. Submitted visuals to Botswana team.
