### ISSUE TITLE
Bostwana Visualization - KP TX_NEW for FY18

### ISSUE THREAD

**Issue by pvinayak001** [ICPI/COP18#48]
Use Imran's tool to get values for TX_NEW targets for KP 2018. 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Botswana/Bots_TX_trends_20180221.xlsx

@shapaklyak

**Comment by pvinayak001** [comment]
Botswana
TX_NEW
FY17: Targets, Q1, APR
FY18: Targets, Q1
Broken out by Key Pop group

**Comment by mehtasp** [comment]
Table with above values sent to Katya

**Comment by shapaklyak** [comment]
thanks!
