### ISSUE TITLE
Botswana - HTS POS  by Population Visualization Support

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#51]
Received from in Country SI Advisor - Amy
HQ SI Advisor - Jason approved all HTS requests

Emailed visualization with following language:
From Katya:
I took out the OU total because when you stack it, it already shows the total amount for the OU so it’s unnecessary. The stacked bar chart then stacks the values correctly. 

It’d be great in making the slides that we try to have consistent colors across charts to represent similar data. So it’d be great if everyone sent in slides but put the actual chart in the slide rather than an image.

**Comment by jaliasd** [comment]
Duplicates #53, closing

**Comment by jb3436** [comment]
Re purposed this ticket (previously about datapack) so we didn't have a duplicate ticket since we are unable to delete github tickets.

**Comment by jb3436** [comment]
Katya completed the request. No follow up needed on this item. Related to all the other Botswana HTS requests #41 #57 #56 #10
