### ISSUE TITLE
Botswana - QC HTS TST POS and TX New by population (Due 2/22 @ 6pm)

### ISSUE THREAD

**Issue by shapaklyak** [ICPI/COP18#52]
Per issue #43 and issue #48 , please QC the graphs on HTS POS and TX NEW in the file linked below 
saved [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FHTS&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

![image](https://user-images.githubusercontent.com/5234106/36543658-11542694-17ed-11e8-8d49-3ba6ec3a4912.png)

**Comment by shapaklyak** [comment]
Please QC the following charts (in the "tables finer disaggs" tab) against Panorama what you can using additional disaggs and clinical cascade visual.  Due (1hr?)


File saved here: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D

![image](https://user-images.githubusercontent.com/5234106/36557057-d97cd824-180f-11e8-9c54-37a4db94d2f3.png)


- Males 15+
- Females 15+
- AGYW  15-24

**Comment by KTmonkey** [comment]
DONE! Gold stars across the board!

**Comment by jb3436** [comment]
Drafted TX_NEW visualization for Botswana with finer age/sex comparing FY16Q1, FY17Q1, FY18Q1. Sent to @shapaklyak to be sent to the country team with the other slides referenced above. Country team is currently doing an analysis.

**Comment by shapaklyak** [comment]
Slidedecks for HTS & TX NEW posted in [Visualizations --> Botswana folder ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Thanks all for the help!
