### ISSUE TITLE
Uganda - SNU Allocation and Disagg Help - N.Solehdin

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#53]
Uganda was a bit worried about their SNU allocations not matching their SNU targets.

They are feeling a bit behind and wanted help making fixes from the Change Log to their disagg tool when they start working with it.

**Comment by achafetz** [comment]
Spent 30min or so with Nadia. 

Added in Change Log 23 to provide SNU allocations not matching their SNU targets. They were using an old version to perform their check and actually in a much better place. 

I also added in a new sheet that has a pivot table of the Allocation tab and then a lookup against the SNU targets tab to see the districts that have a mismatch. Seemed to be a huge help.

**Comment by achafetz** [comment]
Went through and made the fixes for the Disagg Tools from the Change Log Disagg Tools for them to speed things up, so they should actually be in a good place.

**Comment by achafetz** [comment]
reopening due to additions support requested. Question about adding new SNUxIM. Provided immediate overview, but likely more assistance required

**Comment by jb3436** [comment]
FYI @kschlenker

**Comment by achafetz** [comment]
Uganda was experiencing an issue with the Data Pack today in that the Allocation by SNUxIM tab totals didn't match the IM Summary tab. The issue was the result of adding many lines below the bottom of the table. I fixed this by removing all the named ranges from the tab, selecting the full table and reapplying labels. This was also seen in Moz (#62).
