### ISSUE TITLE
Zambia - Submitted DTs for review - L.Mwapela

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#60]
Request for review of Zambia's DTs. 

It doesn't sound like there is an issue; just that they want another pair of eyes on them?

Uploaded versions to [PEPFAR Sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack%2FSubmitted%20DTs%20for%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D).

**Comment by pvinayak001** [comment]
Doing an initial review. Looks like they have not broken out the 25-49 finer age bands in the HTS tool. May need to refer them to the guidance that we just sent out.

**Comment by pvinayak001** [comment]
@kimisatoPC is working with them

**Comment by kimisatoPC** [comment]
General excel TA to remove conditional formatting from DT and general help inputting % allocations for PP_PREV and a few other indicators. Team is now consolidating and should submit completed DT soon. Ticket closed.
