### ISSUE TITLE
South Africa HRH Comparison Request

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/COP18#63]
SA Chair request: 
1) PSNU level comparison of HRH_CURR and PLHIV burden by district. 
2) Site level comparison of HRH_CURR, HRH_STAFF, HTS_TST, HTS_TST POS, Yield, and TX_CURR. Stratify by PLHIV Burden.

**Comment by jb3436** [comment]
Please be sure to confirm the SI advisors approval for this request in addition to the chair.

**Comment by Yabayabadoo** [comment]
Parviez is aware and approves.

**Comment by Yabayabadoo** [comment]
@shazadahmed10 May I please have a site level dataset for RSA with the following indicators?
Periods: FY16 APR, FY17 Target, FY17 APR
HTS_TST (total numerator and modality)
HTS_TST_NEG (total numerator and modality)
HTS_TST_POS (total numerator and modality)
TX_CURR (Total numerator)
TX_NEW (Total numerator)
HRH_CURR (all disaggregates)
HRH_STAFF (All disaggregates)
TX_RET (Total numerator and denominator)

**Comment by shazadahmed10** [comment]
@Yabayabadoo will start this later this afternoon!

**Comment by Yabayabadoo** [comment]
@shazadahmed10 Thank you!

**Comment by shazadahmed10** [comment]
Update: IMs and prioritization levels needed. Dropping UIDs

**Comment by shazadahmed10** [comment]
Finished and uploaded to pepfar.net

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Ad-Hoc%20Analysis/RSA_dataset_HRHcomparison%20V2.xlsx
