### ISSUE TITLE
Week 2 Review Data Packs against Change Log

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#64]
Ensure country teams are using Data Packs that reflect any necessary adjustments from the [Change Log](https://github.com/achafetz/DataPack/wiki/COP18-Data-Pack-Change-Log) around formula fixes. (Email sent to SI advisors 10:30am Sunday)

- [x] Burundi (received)
- [x] Cote d'Ivoire (received)
- [x] Ethiopia (received)
- [x] Haiti (received)
- [x] Kenya (received)
- [ ] Malawi (received)
- [x] Mozambique (received)
- [x] South Africa (received)
- [x] Tanzania (received)
- [x] Ukraine (received)
- [x] Vietnam (received)

repeat process from #13 
 
Best practice would be to copy formulas out of [template](https://github.com/achafetz/DataPack/tree/master/TemplateGeneration). Best option would be to copy formulas out of template (find and replace before)  (find and replace `=` with `'=` to make formula text) and paste into country's tool to compare.

Directions
- Copy Target Calculation tab formulas from row 7 into row 5 of the DP to check.
- Do a find and replace with the `=` to `'=` in row 7 of the DP to check 
- Add a formula to row 8 (overwriting the data there) that compares row 5 (the formula from the template) to row 7 (the formula in the data) `C5=C7`. Note anywhere that this is not the case.
- In addition to this check, make sure you see if 20 and 22 from the Change Log are complete.

Submitted Data Packs located on [PEPFAR SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FDatapack%2FSubmitted%20DPs%20for%20Review&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D).

**Comment by achafetz** [comment]
From A.Knutson re: Haiti's DP
> - OVC_SERV is 'hard entered' into the Target Calculation tab for now.. we're going to get that corrected later today.
 > - I think KP_PREV prisoners num target on the Target Calculation tab has an error in the template - I made a change so it would pull properly from the Assumption tab. Double check.
> - The team needs to clean up some of the IM distribution still - the totals are not lining up with the over SNU targets that they've set. Some of this is related to shifting partners and sites from FY17 to 18 to now 19.
>    - QUESTION:  Do these shifts affect the Disag tool? Maybe we can chat briefly to know how to keep track/manage shifting these adjustments?

**Comment by jb3436** [comment]
Assigned to @imujawar since it is Sunday and our DC colleagues who completed this task previously do not need to be on call today.

**Comment by imujawar** [comment]
Completed review of countries assigned. Please see below screen shot of log:
![capture](https://user-images.githubusercontent.com/18144056/36643834-e246b796-1a48-11e8-8891-6d970011ea28.JPG)

**Comment by imujawar** [comment]
Completed review of countries assigned. Please see below screen shot of log:
![image](https://user-images.githubusercontent.com/18144056/36678121-e9ecca0e-1add-11e8-8536-26e78fad80ff.png)

**Comment by achafetz** [comment]
My review of @imujawar's review
- Burundi
  - need to add in Change Log 22, 24
- Haiti
  - hard coded OVC_SERV targets in, okay
  - need to add in Change Log 22, 24
- Kenya
  - need to add in Change Log 22
- South Africa
  - need to add in Change Log 22, 24
- Ukraine
  - need to add in Change Log 22
- Vietnam
  - need to add in Change Log 22, 24
- CIV
  - need to add in Change Log 22, 24
- Tanzania
  - ART coverage TX_NET_NEW, TX_CURR all hard coded (also for Peds)
  - VMMC_CIRC (and age 15-29) 
  - VMMC HTS (FS) is taking 70% of VMMC_CIRC target rather than the full thing (most country are 100%); looking at APR results, ~93% have a HIVStatus ~ test
- Moz
  - FY19  OVC_SERV Target - most calculated with the inverse which is OK, but there are some that pull from another sheet

**Comment by jb3436** [comment]
Aaron just uploaded Malawi - Aliyah will QC. Final country. @aliyahwakil

**Comment by aliyahwakil** [comment]
Completed review of Malawi DP Below is screenshot of my findings. Please see ![capture](https://user-images.githubusercontent.com/32547566/36797742-bb91397a-1c76-11e8-8400-7e168dfbf7e8.PNG)
