### ISSUE TITLE
Disagg tool support for RSA

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#65]
RSA has questions around the Disagg Tool. Request by P.Nadol via @HoustonJamie. Requested a lunch time meeting.

@HoustonJamie, is P.Hosseini aware/involved?

**Comment by jb3436** [comment]
at OOB, Pooja and Aaron met wit Patrick to discuss support for the disagg tool. They walked him through the process. He said he would try to populate the disagg tool and he would reach out if he had issues. It is COB and he hasn't reached out. Will check in tomorrow to see if he was successful based on the guidance provided and if so will close the ticket.

**Comment by Yabayabadoo** [comment]
@jb3436 linked to disagg tool, PC targets not displaying in datapack. Will check disagg tool to see if PC is listed in RSA's tool as well. Will follow up

**Comment by Yabayabadoo** [comment]
@jb3436 PC is listed in the disagg tool, but its current associated PSNUs are incorrect. I reached out to @achafetz to ask if the incorrect PSNUs can be deleted and replaced with correct ones; he said yes. PC will work with Patrick to update.
