### ISSUE TITLE
Malawi - Retention Assumptions in the Data Pack

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#66]
J.Aberle-Grasse reached out asking to meet around Malawi's retention rates. Requested a meeting with Weathers, Baack and me.

**Comment by achafetz** [comment]
B.Baack -
>...based on the way the data pack moves from projected TX_CURR to the TX_NEW (by applying a calculation to the net_new based on LTFU), we are unable to arrive at a TX_NEW that matches the target exactly. Specifically, it's applying the % LTFU to the tx_net_new, even though this should apply to the TX_NEW.

Following up today.

**Comment by jb3436** [comment]
Aaron reverse engineered the formulas to take out retention and LTFU so that it matched.
