### ISSUE TITLE
Lesotho DataPack Formula Question

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#7]
In key indicator trends tab, the formulas for 2019 targets for each indicator is incorrect (or changed in a previous iteration). 
Question from JP - Should I change the formula or have someone from ICPI assist. 
- Submitted by SI floater/ECT for Lesotho
- Referred to Sadhna/Ebonnie, the SI advisor for Lesotho
- will follow up to see if they need assistance once this is discussed with SI advisor.

**Comment by achafetz** [comment]
Unless the formulas are clearly documented and have been approved by ICPI/SI advisor, no changes should be made to the the Data Pack. 

JP as the floating SI advisor should make the changes to rever the Data Pack formulas back to their original state.

**Comment by jb3436** [comment]
JP is meeting with the in country SI advisor this afternoon and will determine if the country team needs any additional assistance.

**Comment by jb3436** [comment]
Update fromJP: 

He is waiting for an updated datapack from team Lesotho.  If the corrections were made, we can close the ticket, if not, then the team will need support.

**Comment by jb3436** [comment]
No additional support needed at this time.
