### ISSUE TITLE
Haiti - TX_CURR FY18 Target and Q1 site level analysis 

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#70]
SI Advisor request - Knutson
Approved by ICPI
Assigned to Dustyn
Due urgently

**Background**: 
Partner reporting for TX_CURR for Q1, they have HTS and TX NEW  for Q1
If we can come up with a proxy for TX CURR could be for Q1, that would be helpful for the team. 

**Task 1: URGENT**

- Who had an FY18 target and didnt report - send this asap
- List of IMs with/without targets for FY18 (TX_CURR)
- List of Sites with/without targets for FY18 (TX_CURR)

**Task 2**: Later today
List of IMs with results and those missing compared to those that have FY18 targets and should have reported (FY18Q1) for TX_CURR.

List of sites with results and those missing compared to those that have FY18 targets and should have reported (FY18Q1) for TX_CURR.

**Task 3:** Final product is the proxy for those with FY18 targets but who did not report FY18Q1 results for TX_CURR and ESTIMATE based on FY17 Q1 (or your best judgement) what their FY18Q1 results could be.

**Comment by jb3436** [comment]
Met with Jordan to discuss confirming the tx_curr values for FY18 Q1 , Will use those missing values (695) for the 5 sites that should have reported to then recalculate the TX_NET_NEW values since TX_NEW was reported. Dustyn is following up. and will also check DATIM to see if there is an issue with the FactView file calculatoin. FYI @cnichols3h Had a lot of comments on DRT and datalement name restructuring - may want to set up a meeting to talk with them after RPM to discuss their experience more @abrahamagedewICPI @kschlenker

**Comment by jb3436** [comment]
Follow up: will produce the estimates for TX_NET_NEW for the team to review. They are following up with their partners to get the missing values... we will estimate using last years values and produce an updated tx_net_new analysis and will compare reported net new to the revised net new.

**Comment by dp1984** [comment]
We would need the missing values from partners to calculate tx_net_new. Creating proxy results (based on fy17 q1) would only work for one site (Sanatorium de Port-au-Prince) as this is the only site (of the ones that have targets but no results) that contains tx_net_new #'s. Will do a brief follow-up with team to see if further analysis is needed, but considering this issue closed and storing the spreadsheet in this folder 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd-Hoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D






 it has (tx_new)

**Comment by MicSherlock** [comment]
Hi all, I don't see Tx_Net_New calculations? I see this is closed, but please let me know if you would like some help with this one.
