### ISSUE TITLE
Cote d'Ivoire - Case Finding (testing) - Men and Peds - SitexPartner - COB 2/25

### ISSUE THREAD

**Issue by mehtasp** [ICPI/COP18#71]
Create table/visuals for all SitesxPartner in CI, displaying TST_POS, TST_NEG, Yield for Index and IndexMod for Fy17(Apr, all quarters).

Men
Peds

Also including finer age/sex

Contacts: 
Erika venegas@fan.gov
Carine (SI Advisor) traorecc@fan.gov

**Comment by jb3436** [comment]
@imujawar subset the dataset using updated R code.

**Comment by mehtasp** [comment]
Sent Erika visuals by Partner. Excel crashed every time when opening SitexIM dataset. Will condense file as much as possible and update visuals with site level data tomorrow.

**Comment by mehtasp** [comment]
Spoke with Erika, Partner level was enough. They don't need site level anymore. Closing ticket.

**Comment by mehtasp** [comment]
Partner testing data visuals for CIV found [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D)

**Comment by mehtasp** [comment]
Want site level data now

**Comment by jb3436** [comment]
Evidently the in country SI person listed on the ticket did not consult with the HQ SI advisors. We suspended the request until the HQ SI advisors approved (Krebs and Roha).  They followed up with Shaylee to refine the request and have now endorsed it. The HQ SI advisors have submitted a general support request that will absorb the next steps of this request. #80

**Comment by mehtasp** [comment]
Ticket completed and file sent to the Kristens. Closing ticket. Sharepoint link for visuals posted under general support ticket #80
