### ISSUE TITLE
Site Review Tool (Step 3) Request from Pickering

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#72]
Request from Pickering
Urgently need updated template for Site Review Tool

In order for Pickering to get the data in DATIM
Need to paste over the table 
need a completely blank site review tool 

**Steps:**
1. Delete rows 4 and 5 
2. Retain 6
3. Delete rows 7 and below .
4. Select all at every single tab at one time. for rows 4+5
5. For table, suggest writing VBA code to delete the same rows from all tabs adn all tables. 
6. Copy Home tab from disagg tool to the site (minus ICPI logo) and rename from ICPI to "President's Emergency Plan for AIDS Relief (PEFAR) Site Review Tool"

Final Product: Blank Template to be sent to Pickering

**Comment by jason-p-pickering** [comment]
We need two more tabs, which can be blank: 

1) SiteList
2) Mechs

These should appear after the Home tab and before the indicator sheets. 

@pvinayak001

**Comment by pvinayak001** [comment]
@jason-p-pickering Mechs was already a hidden tab so I unhid it. Let me know if I should delete it and make a new one.

**Comment by pvinayak001** [comment]
Posted reverted version on SharePoint. File name is _v3
