### ISSUE TITLE
Ethiopia - KP Visualization 

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#74]
Request: Tisha Wheeler
Approved by SI Advisor Shabeen Ally
Approved by ICPI
Assigned to Pooja @pvinayak001 FYI @kimisatoPC @erinschelar 
Request was facilitated by  and will be monitored by Josh @jaliasd 

- Task 1: Review slides to revise KP data presentation (currently 38 slides) [HERE on SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FEthiopia&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
- Perhaps a Map for KP @dp1984 to update the map they used (see slides - link above)
- Task 2: Meet to discuss the specific ask (Tisha, Pooja, Josh, Jasmine)
- Task 3: Update KP analyses using KP dashboard and KP data sent to ICPI

Background Context:
reason needed - lack of staff/time capacity to update visualizations

Emails from Tisha Wheeler:
From: Tisha Wheeler <twheeler@usaid.gov>

Oh my gosh I just realized we don't have DC support for the slide revision because it is Sunday. I just spoke with Aaron and Josh who said we can create a ticket through the ICPI support team here in Joberg and they will work on the slide modification request or farm it out to whoever can.

I'm adding Aaron and Josh here.

Tisha

---------- Forwarded message ----------
From: Tisha

Sarah

Hi. I am wondering if you and perhaps Jae also can support Kidist today to revise the slides drafted for the Ethiopia PP and KP presentation tomorrow. I have made notes by slide of the modifications I suggest. Based on these notes Kidist will take the lead in determining what is priority. She may also have additional slides or data. I'm emailing you now to get the ball rolling because we are working against the clock. Please be in touch with Kidist and keep me copied. 

-- 
Tisha Wheeler

**Comment by dp1984** [comment]
We need Ethopia team to provide the KP locations if we are to map this.

**Comment by jb3436** [comment]
Ethiopia team did not send additional clarifications of request, source data, parameters, or deadline.  Closing the ticket.
