### ISSUE TITLE
Malawi KP GIS Request

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#75]
Requested by: SI advisor - Ebonnie
Approved by ICPI
Assigned to Dustyn @dp1984 

Sent a slide with KP data tables and they would like it mapped. We have the elements we need to complete a first draft. 2/26, Dustyn will create a first draft and speak with KP technical reviewer Tisha for additional input.

**Comment by dp1984** [comment]
the data need a source. current map is located here for review.

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/GIS/Malawi/Malawi%20-%20FSW%20Hotspots%20and%20Populaton%20Size.png

**Comment by jb3436** [comment]
Emailed Tisha to follow up to have a meeting to review deadline and inputs for request. Sent final product to Tisha, Rachel, and Ebonnie.

**Comment by dp1984** [comment]
updated map with KP_Prev fy17 apr. Added in fsw pop estimates for all districts (data provided by country team)

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/GIS/Malawi/Malawi%20-%20FSW%20Hotspots%20and%20Populaton%20Size%20v2.png

**Comment by dp1984** [comment]
created an alternate map based on feedback from Tisha

that's located here: 
I'd send both maps for her to choose...

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/GIS/Malawi/Malawi%20-%20FSW%20Hotspots%20and%20Populaton%20Size_alt.png
