### ISSUE TITLE
Malawi - OVC Visualization of Q1 Data

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#78]
Received from OVC Technical lead
Approved by ICPI

Gretchen requested TA on the way Malawi was representing their Q1 OVC data. They were not including all data points. I requested they include them and I mocked up a visual for them to use instead of the one they were using. 

![image](https://user-images.githubusercontent.com/13006198/36661739-2ac94036-1aaa-11e8-8e4b-6f0b3596012e.png)

![image](https://user-images.githubusercontent.com/13006198/36663062-5e6dcc5a-1aae-11e8-9364-1ef7aad7fd25.png)

**Comment by shapaklyak** [comment]
@jb3436 do you need any help on this?

**Comment by jb3436** [comment]
They sent in their updtaed Q1 values and I updated the chart to reflect the more appropriate flow. Though not all of the data points are included that probably should be. Ugly redacted version below.  

![image](https://user-images.githubusercontent.com/13006198/36724209-78c78d02-1b80-11e8-9e82-34ea7ad35651.png)

@shapaklyak - nothing needed, thanks! Closing this out now that they confirmed their values.

**Comment by hessionra** [comment]
Malawi slide and OVC HIV Stat Mockup were sent to Gretchen and Alpha on 2/27. 

Documents can can be found on SharePoint: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FMalawi&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence
