### ISSUE TITLE
Namibia DataPack VMMC Quesiton

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#8]
Request from Parviez - SI advisor. 
"I could use some help with Vmmc in Namibia’s datapack. There are chunks that don’t make sense against each other.  Namely cumulative men circumcised is less than target age range cumulative."

Submitted by SI advisor
Approved by ICPI
Assigned to Shaylee and Imran. Pooja is also supporting.

**Comment by imujawar** [comment]
The SNU values entered in the assumptions tab (column AW) for 'Cumulative   Number of Circumcised Men, age 15-29 (end of FY17)' is high compared to the total numerator. The data were entered manually, and do not match with NAT-SUBNAT data (see screenshot below). The source of the manually entered data is unclear and would need to be ascertained. Please see table below for NAT-SUBNAT data entered in DATIM.

[image removed]

The total for 'Cumulative Number of Circumcised Men  (end of FY17)' matches what's in the NAT-SUBNAT datasets, but the 15-29 values don't.

**Comment by jb3436** [comment]
Follow up - country team needs to review their values based on the highlighted issues above and if they need additional assistance, they will reach back out.
