### ISSUE TITLE
Cote d'Ivoire Analytic Support

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#80]
Request from SI advisors Roha and Krebbs
Approved by ICPI
Assigned to Shaylee (#71 #41  ) and Shazad @shazadahmed10 @mehtasp 
Josh to check in with analysts for general support @jaliasd 

Background: CI got stalled in interagency space and was unable due to time/staff to complete some analyses. They are now adjourned for the day so the team can put the analyses together. The HQ SI advisors requested ICPI analytic support to help put together the analyses/visualizations for the team to present. 

Noted that the analysts will be supporting only, not leading anything and the team has committed to setting the parameters and owning the process. 

Will updated ticket with specific requests that come from sitting with the country team. Likely this will be multiple requests, similar to the Botswana situation last week but with more parameters from the beginning.

**Comment by shazadahmed10** [comment]
Update:
The Kristens want tables that display results/targets achievement by Prioritization level, coarse age, sex by partner. They supplied a rough sketch to attempt. Will complete and send to them for further feedback. This is a goal/product that is evolving. 
Time Periods: 17Q1-18Q1
Indicators: HTS_POS, Yield, TX_NEW, TX_CURR

**Comment by mehtasp** [comment]
HTS Case Finding at site level by populations posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence) and emailed to the Kristens

**Comment by shazadahmed10** [comment]
The POS, yield, tx_curr, tx_new by partner tables have been completed, and sent to Kristens:

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence
