### ISSUE TITLE
Cote d'Ivoire - KP estimates tables and Map request (Due Today)

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#82]
Reqested from SI advisors (Krebs and Roha)
Approved by ICPI
Due today
Assigned to Katie I, Erin S, and Dustyn.
Two tasks.

**Task 1**
**Tables** @erinschelar @KTmonkey 
Needed for Cote d Ivoire are the following tables pulling IM data (Heartland and LINKAGES)
1) KP cascade performance by district prioritization and district for all of Cote d Ivoire: KP_PREV, HTC, HTC POS
2) KP yield by district prioritization and district: Show KP HTC, HTC POS 
3) IM level performance of Heartland and LINKAGES across the cascade by district 
4) IM level performance of Heartland and LINKAGES showing just yield (HTC and HTC POS) by district  
 
 **Task 2**
**Maps** @dp1984 @gsarfaty 
5) Cote d Ivoire national Map showing KP Size Estimates and FY17 results
6) Abidjan Map showing district level KP Size Estimates and FY17 results (Abidjan has a lot of detail so they need like a zoom in of Abidjan to see all the details)
7) Cote d Ivoire national Map showing at district level KP yield overlayed on KP Size estimates
8) Abidjan map showing at district level KP yield overlayed

**Comment by KTmonkey** [comment]
Hi, 

Can someone clarify the questions that Erin and I have below pretty please?

1.	KP cascade performance by district prioritization and district for all of Cote d Ivoire: KP_PREV, _HTC_ **(is this asking for HTC not disaggregated or for the KP disagg of HTC?)**, HTC POS
       **1.When you say district, is that SNU1?
       2.What time period since KP_PREV and HTS are on different reporting schedules? Which year’s 
          prioritization would you like us to use?
       3. Can we roll question 2 into question 1 and just add KP yield onto a table that shows KP_Prev, HTC, 
         HCT_Pos?**

2.	KP yield by district prioritization and district: Show KP _HTC_ **(Is this asking for the KP disagg of HTC?)**, HTC POS

3.	IM level performance of Heartland and LINKAGES across the cascade by district
4.	IM level performance of Heartland and LINKAGES showing just yield (HTC and HTC POS) by district
                 **1. Our interpretation is that we can take the table(s) that we make above and filter/slice by the IMs Heartland and Linkages, is that correct?**

**Comment by dp1984** [comment]
@jb3436 I'm not sure if you sent the KP Size Estimates as I'm having issues logging into CDC virtual network. If they did send, would you send those to @gsarfaty ?

**Comment by KTmonkey** [comment]
just sent via email

**Comment by shapaklyak** [comment]
this may help - botswana's testing yield by population group on [pepfar.net](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FBotswana&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Would need to replace the dataset with PSNU x IM for Cote d'Ivoire and repoint the pivot tables to creat visuals and provide time periods that are requested. @jb3436  (see @KTmonkey q's above re: district level, and time period.). I think the yield can be put on one graph as in example below. 

![image](https://user-images.githubusercontent.com/5234106/36682969-625d1db6-1aea-11e8-9f61-ba431d22ec10.png)

![image](https://user-images.githubusercontent.com/5234106/36682997-78458b22-1aea-11e8-948d-73919439cc5f.png)

**Comment by gsarfaty** [comment]
since task 2 also requires yield, @erinschelar and @KTmonkey can you share your dataset with me so we are working from the same thing and not duplicating data pulls/manipulation.

**Comment by KTmonkey** [comment]
Yes ma’am. Will get it to you shortly

**Comment by KTmonkey** [comment]
Hey @gsarfaty I have the dataset and it's almost subset for the indicators needed. Do you want me to put in the yield calculations before giving it to you or do you have that under control? 

We are calculating yield as pos/(pos + neg).

I'm asking because we need it at the IM level for our request and it looks like you need it at the OU level and for Abidjan.

**Comment by gsarfaty** [comment]
@KTmonkey I need at their PSNU level (health district/level5). Not sure which FV dataset you are starting from. If you are using OUxIM, I will start from scratch. Thanks!

**Comment by KTmonkey** [comment]
PSNUxIM

**Comment by KTmonkey** [comment]
CDI subset dataset uploaded to pepfar.net, link below.

This data is from the PSNUxIM dataset


![image](https://user-images.githubusercontent.com/34682571/36689504-9f40f212-1afd-11e8-971c-eb9505c8c8c8.png)

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by gsarfaty** [comment]
I used the CDI subset_3 dataset Katie posted to create pivots for MSM, and FSW. Pivots have just HTS_TST_NEG and HTS_TST_POS. I will do the yield calcs in Arc (unless anyone feels strongly otherwise). Can @erinschelar, @KTmonkey, or other QC them quickly before I map? Also please check KP_PREV for FSW as it does not match what the team sent in their spreadsheet. KP_PREV for MSM does match their spreadsheet.

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FGIS%2FCote%20d%27Ivoire&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by KTmonkey** [comment]
@erinschelar & @shapaklyak please QC - https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by shapaklyak** [comment]
@KTmonkey @erinschelar HTS_TST POS matches for key populations in panorama. The total HTS TST completed for key pops matches between the total for all SNUs in the SNU tab (and when all IMs selected) in the IM tab.

**Comment by shapaklyak** [comment]
@gsarfaty downloading your file now to cross-check

**Comment by shapaklyak** [comment]
Task 1 complete by @KTmonkey @erinschelar & I. QC'd against Pano & Prevention Tables.
File saved in[ COP Support > Visualizations > CIV ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)


@gsarfaty as discussed on slack - include "N" as filter and other filters for matched results. good to go!

@jb3436 can you forward the attachment to the SI advisors/original requester.

Posted two files - one with dataset and another with just tables (reduced file size should be easier for download)
![image](https://user-images.githubusercontent.com/5234106/36698793-c5ee76da-1b18-11e8-9ef0-436a27b7a4a5.png)


1. KP cascade performance by district prioritization and district for all of Cote d Ivoire: KP_PREV, HTC, HTC_POS
2. KP yield by district prioritization and district: Show KP HTC, HTC POS
3. IM level performance of Heartland and LINKAGES across the cascade by district
4. IM level performance of Heartland and LINKAGES showing just yield (HTC and HTC POS) by district

**Comment by gsarfaty** [comment]
Map outputs have been added to pepfar.net: [COP Support > GIS > Cote d'Ivoire](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FGIS%2FCote%20d%27Ivoire&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

@dp1984 - map packages are also there in case edits are needed, or questions arise, when you all wake up in Jo'burg.

**Comment by jb3436** [comment]
Sent email to the team with the products attached and with links to the sharepoint folder. 

Dear Krebs, Roha, and Tisha, 

Attached, please find the products for task one and two. 

Task 1 – Tables
Attached is an excel file with the tables. If you would like the dataset it is on sharepoint [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FC%27IV&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)
1.	KP cascade performance by district prioritization and district for all of Cote d Ivoire: KP_PREV, HTC, HTC_POS
2.	KP yield by district prioritization and district: Show KP HTC, HTC POS
3.	IM level performance of Heartland and LINKAGES across the cascade by district
4.	IM level performance of Heartland and LINKAGES showing just yield (HTC and HTC POS) by district

Task 2 – Maps 
Maps and the dataset for the maps on SharePoint [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FGIS%2FCote%20d%27Ivoire&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)
1.	Cote d Ivoire national Map showing KP Size Estimates and FY17 results
2.	Abidjan Map showing district level KP Size Estimates and FY17 results (Abidjan has a lot of detail so they need like a zoom in of Abidjan to see all the details)
3.	Cote d Ivoire national Map showing at district level KP yield overlayed on KP Size estimates
4.	Abidjan map showing at district level KP yield overlayed 

Best, 

ICPI
