### ISSUE TITLE
Haiti - find/replace Strange Characters in Disagg Tool (due this evening)

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#83]
Request from Audrey (SI advisor)
Approved by ICPI
Assigned Pooja

Affected:
- Datapack 
- Disagg tool
- HTS disagg tool

**Description of issue:**
SNUs in the disagg tool have strange characters. These need to be replaced with the correct version that you can find on the assumptions tab of datapack, which has the correct french characters for SNUs

The names need to be replaced in EVERY tab of the disagg tool and HTS disagg tool. 

This evening - before 7pm

**Comment by pvinayak001** [comment]
Change log:


Old   Name | Replaced With
Anse   ÃƒÂ  Veau | Anse-à-Veau
Cap-HaÃƒÂ¯tien | Cap-Haïtien
ChardonniÃƒÂ res | Chardonnières
Fort   LibertÃƒÂ© | Fort-Liberté
GonaÃƒÂ¯ves | Gonaïves
Grande   RiviÃƒÂ¨re du Nord | Grande-Rivière-du-Nord
JÃƒÂ©rÃƒÂ©mie | Jérémie
LimbÃƒÂ© | Limbé
MÃƒÂ´le Saint   Nicolas | Môle-Saint-Nicolas
MiragoÃƒÂ¢ne | Miragoâne
Saint-RaphaÃƒÂ«l | Saint-Raphaël
ValliÃƒÂ¨res | Vallières
