### ISSUE TITLE
Haiti request: site-level and IM level TB/HIV FY17APR results and selected disaggs. in a single excel file

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/COP18#87]
Hi all - I am requesting help pulling FY17 APR data on the TB/HIV indicators into a single excel file.  I have a table shell excel version of exactly what we need.  I uploaded the table shell under the Ad Hoc analysis folder.  I think this request would take less than an hr.  Is someone able to get to this request before 11am Joburg time on 2/27?  If not, I can take the request back at this time.  Thanks.

**Comment by shapaklyak** [comment]
I'll take a look at the shell in a bit.

**Comment by cnichols3h** [comment]
@shapaklyak - thanks!

**Comment by shapaklyak** [comment]
@cnichols3h just double checking that you need TX_CURR in there?

**Comment by anu87** [comment]
Do you need any help? I have R script for subsetting site-IM data

**Comment by cnichols3h** [comment]
@shapaklyak Yes, I need TX_CURR.  @anu87 thanks!  I think it's fine as a one time request & I believe Katya already worked on it.

**Comment by shapaklyak** [comment]
@cnichols3h please see file in pepfar.net on [COP support --> Ad hoc analysis ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

Two files posted, one with pivot tables off with the site x IM Haiti dataset subset for the indicators requested and another file with just the tables. Please review before pasting into your file for order as there wasn't a TX TB den.pos.

Note - not QC'd as Panorama is down. 

![image](https://user-images.githubusercontent.com/5234106/36702537-77fe51e0-1b25-11e8-935a-6ce26eb184a6.png)

**Comment by cnichols3h** [comment]
@shapaklyak great - thank you!  

Yes, this will be tricky for us as we are still making new materials to present & verifying numbers in Pano.

**Comment by cnichols3h** [comment]
@shapaklyak hmm that value does exist.  i already had the OU level value for Haiti from something else. 
 TX_TB den. pos should = 2626.

**Comment by shapaklyak** [comment]
@cnichols3h ok taking another look, can you please post to pepfar.net the file you're referring to

**Comment by shapaklyak** [comment]
@cnichols3h see the uploaded v3 file on [pepfar.net](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FAd%2DHoc%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence) - Katie & I did our best to QC against final.datim. there's a QC tab within the file with favorite links that you can access (drag in Haiti). 

![image](https://user-images.githubusercontent.com/5234106/36707498-915fb856-1b3c-11e8-8ec9-85bb069d509a.png)

**Comment by cnichols3h** [comment]
@shapaklyak @KTmonkey - you all are the best.  thanks!
