### ISSUE TITLE
Ukraine -> Request for help

### ISSUE THREAD

**Issue by achafetz** [ICPI/COP18#89]
B. Gern dropped by the table this morning and wanted assistance since Ukraine is now reducing a lot of their targets and had a few questions. He was going to drop by later this morning to go through then and ask specifics.

**Comment by imujawar** [comment]
Ukraine needed to increase it's adult TX_NEW numbers in the DataPack, without changing retention. 

Advised as follows:
- Increase TX_CURR FY19 coverage.
- Decrease TX_CURR achievement for FY18 so expected FY2018 results will be lower. 

This will increase TX_NEW numbers. 

![image](https://user-images.githubusercontent.com/18144056/36775546-84f53484-1c30-11e8-89bf-bcdaa5ce58a9.png)

**Comment by achafetz** [comment]
B.Gern & M.Au came by trying try to figure out how to zero out their peds targets since they are getting out of peds treatment in COP18. We changed their expected FY18 results to 0%
