### ISSUE TITLE
DRC Denominators Request - Spectrum

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#9]
Request from JAG to assist DRC with re-running spectrum estimates. 

Request from SI (JAG)
Approved by Josh
Assigned to Josh

**Comment by jb3436** [comment]
Meeting at 12:30 to discuss request and next steps.

**Comment by jaliasd** [comment]
Liaised  with UNAIDS to troubleshoot. Further info need from DRC country team before further action required.
