### ISSUE TITLE
Malawi - HRH

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#90]
Requested from SI Advisor (Ebonnie)
Approved by ICPI
Assigned to Shaylee. 

Need to request slides referenced in original email (JB) - they sent slides from South Africa from the HRH analysis Yaa and Shazad worked on #63 

**Background:**
- Malawi trying to address the correlation between the clinical cascade and HRH investments. 
- Want to answer several questions, one is how has HRH improved results
- Looking for correlative analysis on the HRH data and clinical cascade results
- Assuming the changes in HRH salary support (increasing by nearly 200%), pre-service training (maintenance) and in-service training (discontinuation?) from Cop 16 through to COP 18 are based on results in the clinical cascade but realize it may also be due to  budget changes. The data behind these changes may also help to describe the impact of HRH on clinical cascade

**Comment by Yabayabadoo** [comment]
@jb3436 the slide deck attached in the email is for Malawi? It would be good to know what the analytic ask is: i.e. do they want a comparison of total FTEs against clinical cascade or specific cadres to specific indicators? Also what level should this be? Site, district, province?

**Comment by Yabayabadoo** [comment]
@wvp3 @mehtasp @jb3436 The analyses look to be using country level data that the MER indicator would not provide. For example, Lay workers cannot be disaggregated further by lay type. Please advise

**Comment by jb3436** [comment]
@Yabayabadoo I found the SA slides. They are posted [here](
https://www.pepfar.net/ou/southafrica/HQ%20Collaboration/Forms/AllItems.aspx?RootFolder=%2Fou%2Fsouthafrica%2FHQ%20Collaboration%2FCOP%202018%20%E2%80%93%20FY%202019%2FRPM%2FRPM%202%20Presentations&FolderCTID=0x0120002EBEB387668FB04AB49607B828E1D04600D4EADCB03357C1499149664CDC5A310C&View=%7BFC8D18B8%2D9028%2D4FBB%2D9366%2D809A90ED8A80%7D
). 
The request is to recreate this slide @mehtasp @Yabayabadoo 
![image](https://user-images.githubusercontent.com/13006198/36719683-c391bdba-1b73-11e8-89c0-d8da3bd2fde5.png)

**Comment by jb3436** [comment]
Confusion between acting SI advisor (Ebonni) and Permanent SI advisor (Parviez) and the floating HRH technical lead (Vamsi) on the need for the request. Also confusion about who this is assigned to. Shaylee is assigned, Yaa requested the same for South Africa and was consulted but was not assigned to this task! Received conflicting messages from all and opted to complete the analysis and send it along regardless of the internal confusion.

**Comment by mehtasp** [comment]
Steps:
1) D/l Malawi's SitexIM Factview dataset
2) Subset for TX_CURR, HRH_CURR
3) Create pivot with Sites, FY17 APR (TX_CURR and HRH_CURR) and FY17 Targets (TX_CURR) disaggregating by Total Num
4) Sort by Sites with highest TX_CURR targets and create graph with top 20 sites

Completed and emailed to the group. Posted [here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FVisualizations%2FMalawi&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence) on Sharepoint

**Comment by jb3436** [comment]
Redacted version of slide below. 
![image](https://user-images.githubusercontent.com/13006198/36724774-2da3166e-1b82-11e8-9a73-2eedddcfba53.png)
