### ISSUE TITLE
Burundi (URGENT) DataPack Hierarchy Help

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP18#92]
Request received from SI Advisor (Yesenia)
Approved by ICPI
Assigned to Aaron and Pooja

**Request**
Based on this morning's discussion, Burundi will need to make a change to our DATIM hierarchy.  We need to combine/cluster Bujumbura Mairie and Bujumbura Rural into Bujumbura.  Also, we are proposing (with Chair support) to reactivate Gitega, which already exists in DATIM and the Datapack--just noting as an FYI in case of consequence. 

Apart from the aforementioned, no other changes.

Please let me know what is required, timelines and next steps for the update.  

I will also swing by the ICPI helpdesk again for follow up.

**Comment by achafetz** [comment]
sent [cluster form](https://github.com/achafetz/DataPack/blob/master/RawData/COP18Clusters.csv) to Y.Saulino to complete and then I can regenerate the Data Pack (will be done off FV Q4v3_2, current is v2_1).

Data Pack should be a quick run (<20min) once the file is received; the DTs will take longer since I have to access the server and move files over (on this internet with poor bandwidth)

**Comment by achafetz** [comment]
Just clustering two districts into 1. Received file at 1pm and started on DP creation.

**Comment by achafetz** [comment]
Network issues, but Burduni DTs were created and passed along to Y.Saulino.

**Comment by jb3436** [comment]
Not using a denom for one province that has now been clustered. THey don't want to be constrained. How do they modify the data pack so that 

The coverage rate is capped that is built in 

Yesenia will send the datapack to Noah @noahbartlett for him to help with the updated datapack in the same way he did previously in DC. Will cc @achafetz 

Other ask: 
Drafting cascades by population/finer age/sex - wants someone to QC her pivots and advise on layout of visualizaitons she has already started. 
Yesenia will send an email with this information @hessionra 

Also asked about support hours of operation and I let her know the DC team was available.

**Comment by noahbartlett** [comment]
I've been in touch with Yesenia on this. I am available to help on this as soon as they sort out laptop power issues.

**Comment by noahbartlett** [comment]
Solved the Burundi DP issues:

1) Reduced Anticipated achievement of FY18 TX_CURR target to 72% for Kirundo. 
2) Showed YS how to change FY17 and 18 TX_CURR numbers in the DATIM Indicator tab for Gitega (where there were no previous PEPFAR results and they want to use Global Fund numbers instead).

Also looked at her age/sex pivot tables for building cascades and walked her through which age filters to use for which indicators.
