### ISSUE TITLE
Haiti request for 2 maps with KP data

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/COP18#95]
Hi! I am submitting a request for two maps on behalf of the Haiti team. The request is for the following maps:
1) size estimate (density) by department, SNU1 with MSM and FSW prevalence. 
2) size estimate by department, SNU1 with FY17 results for KP_PREV overlayed in a bubble.
I have a table with size estimations for map #1, which I will upload to the COP18 support, Visualizations, Haiti folder.
This request might be best for a colleague in DC.  It would be preferable to have this soonish as Haiti team hopes to outbrief tomorrow.

**Comment by cnichols3h** [comment]
@gsarfaty - thank you.  I will send you a follow up email as I decided not to post the KP file on pepfar.net, but will send to you.

**Comment by gsarfaty** [comment]
KP_PREV data QC'd by @shapaklyak 

Relevant materials are here: [COP18 Support > GIS > Haiti](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FGIS%2FHaiti&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

Outputs sent to @cnichols3h with @jb3436 and ICPI copied.

**Comment by cnichols3h** [comment]
@gsarfaty @shapaklyak this is great!  thanks again.

**Comment by dp1984** [comment]
The team is wondering if there can be more of a range for the KP results to better differentiate programs on the map (see the request below from the team).  Is there any way you can help the Haiti team with this this morning?

**Comment by dp1984** [comment]
sent maps to @cnichols3h & updated versions are located [here on sharepoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP18%2FSupport%20Requests%20and%20Tracker%2FGIS%2FHaiti&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)
