### ISSUE TITLE
Moz request: build out Rasta Table (Stoplight/Heat Table) projection tool

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/COP18#96]
Requested by Moz via Jamie. 
Additional capabilities: build out projections for ANC, TB, VMMC and previously diagnosed so these can also be compared. (See notes tab in Moz rasta table file for notes)

-Need updated DP from Jamie

**Comment by jb3436** [comment]
Received updated datapack from Joel, the in country M&E person. Shazad will create the tables and send back this evening.

**Comment by jaliasd** [comment]
@jb3436  datapack or disag tool? If the latter, was it complete?

**Comment by jb3436** [comment]
@jaliasd , Joel gave us the most recent version of the datapack. Not sure about the completeness of it... it is complete enough to be able to do the stoplight tables.

**Comment by shazadahmed10** [comment]
Completed tool with "other entry points" numbers also built in.
sent to Joel and Moz team.
link: 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Visualizations/Mozambique/Moz%20Rasta%20Table%20Tool.xlsx
