### ISSUE TITLE
Haiti request - visualizations w/ KP data

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/COP18#97]
Hi all - I've got a request from the Haiti team to pull data for their KP partners (there are 3).  The request is for a visualization w/ quarterly data by cascade: HTS, HTS_POS, TX_NEW, TX_CURR.  1 set of visualizations by partner and quarter (FYQ1-4, FY18 Q1).  1 set by district w/ the data aggregated at the partner level, for the same time frame.  

I will send a follow up email to whoever is able to help.  Thanks.

**Comment by hessionra** [comment]
Assigning @shapaklyak as a secondary analyst for now, reaching out to @aliyahwakil and @anu87 about their availability to be primary analyst.

**Comment by hessionra** [comment]
@cnichols3h would you be able to post additional info on SharePoint or here? Do you need OU level, PSNU, or by age groups? Thank you!

**Comment by anu87** [comment]
I will get to this in an hour.

**Comment by cnichols3h** [comment]
@anu87 awesome - thank you.  We will need by partner and by district (SNU 1).  I will send you something additional via email.

**Comment by shapaklyak** [comment]
@cnichols3h please include all assigned on this ticket.

**Comment by anu87** [comment]
do you need site level data or PSNU_IM works?

**Comment by cnichols3h** [comment]
@anu87 - psnu X IM is fine.  We need by partner and another visualization by SNU1.  Thanks!
@jb3436 @shapaklyak @hessionra @ICPIadmin

**Comment by anu87** [comment]
@cnichols3h @hessionra @shapaklyak @jb3436 @ICPIadmin I see two partners under Implementation Mechanism – FOSREF & FOSREF 1925. Should I pull in both and combine them?

**Comment by cnichols3h** [comment]
@hessionra @shapaklyak @jb3436 @ICPIadmin Yes, please combine the results and targets listed under these partners and treat them as 1 partner.

**Comment by anu87** [comment]
@cnichols3h @hessionra @shapaklyak @jb3436 @ICPIadmin see: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Ad-Hoc%20Analysis/Haiti_PSNU_IM_FY18_KPPartner_Issue97.xlsx

Is this okay?

**Comment by shapaklyak** [comment]
@anu87 i'm not sure the quarters across Fy17 -Fy18q1 should be stacked on top of each other. @cnichols3h does this represent the data how you needed? @anu87 has this been cross-checked against other data (datim or another analyst?)

**Comment by anu87** [comment]
@cnichols3h @shapaklyak I am making changes -please wait for the new version

**Comment by cnichols3h** [comment]
@shapaklyak 
@anu87 - thank you!  yes, can you switch the x and y axes?  can you also add a graph for hts_tst_pos (not sure if it's there but mislabeled)?  can you also add in a line above each bar that represents target data?
for the other request, this would be by district on the x-axis and have the data for the partners stacked (we will also want to know which partner is which).  there will also be 3 graphs: one with hts_tst, one with hts_tst_pos and one with tx_new.  also showing results in a bar graph and a line above each bar as the target.  for this one you can do just the most recent time period of FY18 Q1.

**Comment by shapaklyak** [comment]
@cnichols3h , @anu87 is making the changes now and will repost. need to QC

**Comment by anu87** [comment]
@cnichols3h @shapaklyak please see this and let me know if you need any changes: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP18/Support%20Requests%20and%20Tracker/Ad-Hoc%20Analysis/Haiti_PSNU_IM_FY18_KPPartner_Issue97.xlsx

**Comment by cnichols3h** [comment]
@anu87 @shapaklyak this is great. thank you!  i can take it from here.  i still may tweak things depending on exactly what the team wants, but getting this all started was really helpful.
