### ISSUE TITLE
Help QC Coverage tables for Tanzania HeatMap, related to #86

### ISSUE THREAD

**Issue by imujawar** [ICPI/COP18#99]
This QC request is related to QC-ing HeatMap tables. #86 

The Raster table/Heat map I've created from the PLHIV raw data provided for FY17 in tab **‘FY19 PLHIV Updated Spectrum_v2’**. 

Please see below what needs to be checked:

- [x] ‘Rasta_Raw’ is reading data correctly from the first tab ‘FY19 PLHIV Updated Spectrum_v2’. 
- [x] Tab ‘Final_Raster_Table’ tab is reading correctly from ‘Rasta_Raw’ tab. 
- [x] Double check the conditional formatting in the ‘Final_Raster_Table’ for coverage.

**Comment by shapaklyak** [comment]
@imujawar please redact the image - block out the SNUs or post to pepfar.net

**Comment by wvp3** [comment]
All three look good to me.  I think it's right.
